In [3]:
"""import os
import json
import json5
from time import sleep
#from openai import OpenAI
from tqdm import tqdm
import numpy as np
import pandas as pd
import faiss
from sentence_transformers import SentenceTransformer
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from gensim.utils import simple_preprocess"""

'import os\nimport json\nimport json5\nfrom time import sleep\n#from openai import OpenAI\nfrom tqdm import tqdm\nimport numpy as np\nimport pandas as pd\nimport faiss\nfrom sentence_transformers import SentenceTransformer\nfrom gensim.models.doc2vec import Doc2Vec, TaggedDocument\nfrom gensim.utils import simple_preprocess'

## 3. resume extract and conversion from json to text

In [4]:
import os
import json
from tqdm import tqdm
from dotenv import load_dotenv
from langchain_community.llms import Ollama

In [5]:
os.environ.setdefault("LLM_BACKEND", "ollama")
os.environ.setdefault("OLLAMA_MODEL", "mistral")

'mistral'

In [6]:
def weight_resume_llm(cv_text):
    prompt = f"""
    You are an expert resume analyst.

    Your task is to identify the candidate’s CORE PROFESSIONAL PROFILE.
    Focus on clarity and precision. Avoid noise and redundancy.

    RULES (IMPORTANT):
    - Identify ONE primary professional role only
    - Identify at most ONE secondary role (optional)
    - Select NO MORE THAN 6 core skills
    - Select NO MORE THAN 4 experience themes
    - Use short, clear, professional wording
    - Do NOT repeat skills in multiple sections
    - Do NOT add explanations or prose

    OUTPUT FORMAT (STRICT – follow exactly):

    === CORE PROFILE ===
    PRIMARY_ROLE: <short role name>
    SECONDARY_ROLE: <short role name or NONE>

    CORE_SKILLS:
    - <skill> (expert | advanced | intermediate)
    - <skill> (expert | advanced | intermediate)

    CORE_EXPERIENCE_THEMES:
    - <short theme>
    - <short theme>

    KEYWORDS:
    <keyword1> | <keyword2> | <keyword3> | <keyword4> | <keyword5>

    CV:
    ----------------
    {cv_text}
    ----------------

    """
    llm = Ollama(
    model="mistral",
    base_url="http://127.0.0.1:11434",
    timeout=300
    )
    response = llm.invoke(prompt)
    return response

### Conversion without experiences description

In [7]:
def clean_string(s):
    return str(s).replace("\n", " ").strip()

In [8]:
def json_to_text(data):
    parts = []

    skills = data.get("skills")
    if skills:
        skills_list = [clean_string(s) for s in (skills if isinstance(skills, list) else [skills]) if s]
        parts.append("Skills: " + "; ".join(skills_list))

    experience = data.get("experience")
    if experience:
        exp_list = []
        for e in experience:
            title = clean_string(e.get("title", ""))
            company = clean_string(e.get("company", ""))
            years = clean_string(e.get("years", ""))
            exp_list.append(" ".join(filter(None, [title, "at" if title and company else "", company, years])))
        parts.append("Experience: " + "; ".join(exp_list))

    education = data.get("education")
    if education:
        edu_list = []
        for e in education:
            degree = clean_string(e.get("degree", ""))
            school = clean_string(e.get("school", ""))
            edu_list.append(" ".join(filter(None, [degree, "at" if degree and school else "", school])))
        parts.append("Education: " + "; ".join(edu_list))

    certifications = data.get("certifications")
    if certifications:
        cert_list = [clean_string(c) for c in (certifications if isinstance(certifications, list) else [certifications]) if c]
        parts.append("Certifications: " + "; ".join(cert_list))

    summary = data.get("summary")
    if summary:
        parts.append("Summary: " + clean_string(summary))

    base_text="\n".join(parts).strip()
    """    
    try:
        weighted_profile = weight_resume_llm(base_text)
        return base_text + "\n\n" + weighted_profile
    except Exception as e:
        print("⚠️ LLM weighting failed:", e)
        return base_text"""
    return base_text

In [9]:
"""def process_json_folder(input_folder, output_folder, limit=50):
    os.makedirs(output_folder, exist_ok=True)
    json_files = sorted([f for f in os.listdir(input_folder) if f.endswith(".json")])[:limit]
    for filename in tqdm(json_files, desc=f"Processing {len(json_files)} JSON files"):
        input_path = os.path.join(input_folder, filename)
        with open(input_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        output_path = os.path.join(output_folder, f"{os.path.splitext(filename)[0]}.txt")
        with open(output_path, "w", encoding="utf-8") as out:
            out.write(json_to_text(data))"""
def process_json_folder(input_folder, output_folder):
    os.makedirs(output_folder, exist_ok=True)
    for filename in tqdm([f for f in os.listdir(input_folder) if f.endswith(".json")], desc="Processing JSON files"):
        input_path = os.path.join(input_folder, filename)
        with open(input_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        output_path = os.path.join(output_folder, f"{os.path.splitext(filename)[0]}.txt")
        with open(output_path, "w", encoding="utf-8") as out:
            out.write(json_to_text(data))

### Conversion with experiences description

In [10]:
def json_to_text1(data):
    parts = []
    skills = data.get("skills")
    if skills:
        skills_list = [clean_string(s) for s in (skills if isinstance(skills, list) else [skills]) if s]
        parts.append("Skills: " + "; ".join(skills_list))

    experience = data.get("experience")
    if experience:
        exp_list = []
        for e in experience:
            title = clean_string(e.get("title", ""))
            company = clean_string(e.get("company", ""))
            start_date = clean_string(e.get("start_date", ""))
            end_date = clean_string(e.get("end_date", ""))
            description = clean_string(e.get("description", ""))
            
            exp_parts = []
            if title:
                exp_parts.append(title)
            if company:
                exp_parts.append(f"at {company}")
            if start_date or end_date:
                date_range = f"({start_date} - {end_date})".replace("  ", " ").strip()
                exp_parts.append(date_range)
            if description:
                exp_parts.append(f": {description}")
            
            exp_list.append(" ".join(exp_parts))
        
        parts.append("Experience: " + " | ".join(exp_list))

    education = data.get("education")
    if education:
        edu_list = []
        for e in education:
            degree = clean_string(e.get("degree", ""))
            school = clean_string(e.get("school", ""))
            edu_list.append(" ".join(filter(None, [degree, "at" if degree and school else "", school])))
        parts.append("Education: " + "; ".join(edu_list))

    certifications = data.get("certifications")
    if certifications:
        cert_list = [clean_string(c) for c in (certifications if isinstance(certifications, list) else [certifications]) if c]
        if cert_list:
            parts.append("Certifications: " + "; ".join(cert_list))

    summary = data.get("summary")
    if summary:
        parts.append("Summary: " + clean_string(summary))

    base_text="\n".join(parts).strip()
    """
    try:
        weighted_profile = weight_resume_llm(base_text)
        return base_text + "\n\n" + weighted_profile
    except Exception as e:
        print("⚠️ LLM weighting failed:", e)
        return base_text"""
    return base_text

In [11]:
def process_json_folder1(input_folder, output_folder):
    os.makedirs(output_folder, exist_ok=True)
    for filename in tqdm([f for f in os.listdir(input_folder) if f.endswith(".json")], desc="Processing JSON files"):
        input_path = os.path.join(input_folder, filename)
        with open(input_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        output_path = os.path.join(output_folder, f"{os.path.splitext(filename)[0]}.txt")
        with open(output_path, "w", encoding="utf-8") as out:
            out.write(json_to_text1(data))

In [12]:
# first approach
process_json_folder("./data/resume_extract_json", "./data/resume_extract_text")

Processing JSON files: 100%|██████████| 2549/2549 [00:28<00:00, 88.53it/s]

In [13]:
# second approach
process_json_folder1("./data/resume_extract_json", "./data/resume_extract_text1")

Processing JSON files: 100%|██████████| 2549/2549 [00:01<00:00, 1280.23it/s]

## 4. resume embedding

### Embedding with smaller extracted text

In [14]:
import os
import json
import numpy as np
import faiss
from tqdm import tqdm
from sentence_transformers import SentenceTransformer
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from gensim.utils import simple_preprocess

Embedding with SentenceTransformer

In [15]:
model = SentenceTransformer("all-MiniLM-L6-v2")

input_folder = "./data/resume_extract_text"
txt_files = [f for f in os.listdir(input_folder) if f.endswith(".txt")]

batch_size = 32
embeddings_list = []

for start in tqdm(range(0, len(txt_files), batch_size), desc="Encoding resumes"):
    batch_files = txt_files[start:start + batch_size]
    texts = []
    for file in batch_files:
        path = os.path.join(input_folder, file)
        try:
            with open(path, "r", encoding="utf-8") as f:
                texts.append(f.read())
        except Exception as e:
            print(f"Error reading {file}: {e}")
            texts.append("")

    batch_embeddings = model.encode(texts, convert_to_numpy=True, batch_size=batch_size)
    batch_embeddings /= np.linalg.norm(batch_embeddings, axis=1, keepdims=True)
    embeddings_list.append(batch_embeddings)

all_embeddings = np.vstack(embeddings_list)
faiss_index = faiss.IndexFlatIP(all_embeddings.shape[1])
faiss_index.add(all_embeddings)
faiss.write_index(faiss_index, "./data/resume_index.faiss")

with open("./data/resume_index_mapping.json", "w", encoding="utf-8") as f:
    json.dump(txt_files, f, ensure_ascii=False, indent=4)

Encoding resumes: 100%|██████████| 80/80 [00:30<00:00,  2.66it/s]

Embedding with Doc2Vec

In [16]:
input_folder = "./data/resume_extract_text"
txt_files = [f for f in os.listdir(input_folder) if f.endswith(".txt")]

tagged_data = []
for idx, file in enumerate(tqdm(txt_files, desc="Preparing documents")):
    path = os.path.join(input_folder, file)
    try:
        with open(path, "r", encoding="utf-8") as f:
            text = f.read()
            tokens = simple_preprocess(text)
            tagged_data.append(TaggedDocument(words=tokens, tags=[str(idx)]))
    except Exception as e:
        print(f"Error reading {file}: {e}")
        tagged_data.append(TaggedDocument(words=[], tags=[str(idx)]))

print("Training Doc2Vec model...")
model = Doc2Vec(
    vector_size=300,
    window=5,
    min_count=2,
    workers=4, 
    epochs=40,
    dm=1,
    seed=42
)

model.build_vocab(tagged_data)
model.train(tagged_data, total_examples=model.corpus_count, epochs=model.epochs)

print("Generating embeddings...")
all_embeddings = np.array([model.dv[str(i)] for i in range(len(txt_files))], dtype=np.float32)
all_embeddings /= np.linalg.norm(all_embeddings, axis=1, keepdims=True)

faiss_index = faiss.IndexFlatIP(all_embeddings.shape[1])
faiss_index.add(all_embeddings)
faiss.write_index(faiss_index, "./data/resume_index_doc2vec.faiss")

with open("./data/resume_index_mapping_doc2vec.json", "w", encoding="utf-8") as f:
    json.dump(txt_files, f, ensure_ascii=False, indent=4)

model.save("./data/doc2vec_resume.model")

print(f"✅ Doc2Vec embeddings created: {all_embeddings.shape}")

Preparing documents: 100%|██████████| 2549/2549 [00:00<00:00, 3001.85it/s]

Training Doc2Vec model...

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Generating embeddings...
✅ Doc2Vec embeddings created: (2549, 300)

### Embedding with bigger extracted text

Embedding with SentenceTransformer

In [17]:
model = SentenceTransformer("all-MiniLM-L6-v2") #"all-mpnet-base-v2"

input_folder = "./data/resume_extract_text1"
txt_files = [f for f in os.listdir(input_folder) if f.endswith(".txt")]

batch_size = 32
embeddings_list = []

for start in tqdm(range(0, len(txt_files), batch_size), desc="Encoding resumes"):
    batch_files = txt_files[start:start + batch_size]
    texts = []
    for file in batch_files:
        path = os.path.join(input_folder, file)
        try:
            with open(path, "r", encoding="utf-8") as f:
                texts.append(f.read())
        except Exception as e:
            print(f"Error reading {file}: {e}")
            texts.append("")

    batch_embeddings = model.encode(texts, convert_to_numpy=True, batch_size=batch_size)
    batch_embeddings /= np.linalg.norm(batch_embeddings, axis=1, keepdims=True)
    embeddings_list.append(batch_embeddings)

all_embeddings = np.vstack(embeddings_list)
faiss_index = faiss.IndexFlatIP(all_embeddings.shape[1])
faiss_index.add(all_embeddings)
faiss.write_index(faiss_index, "./data/resume_index1.faiss")

with open("./data/resume_index_mapping1.json", "w", encoding="utf-8") as f:
    json.dump(txt_files, f, ensure_ascii=False, indent=4)

Encoding resumes: 100%|██████████| 80/80 [00:31<00:00,  2.57it/s]

Embedding with Doc2Vec

In [18]:
input_folder = "./data/resume_extract_text1"
txt_files = [f for f in os.listdir(input_folder) if f.endswith(".txt")]

tagged_data = []
for idx, file in enumerate(tqdm(txt_files, desc="Preparing documents")):
    path = os.path.join(input_folder, file)
    try:
        with open(path, "r", encoding="utf-8") as f:
            text = f.read()
            tokens = simple_preprocess(text)
            tagged_data.append(TaggedDocument(words=tokens, tags=[str(idx)]))
    except Exception as e:
        print(f"Error reading {file}: {e}")
        tagged_data.append(TaggedDocument(words=[], tags=[str(idx)]))

print("Training Doc2Vec model...")
model = Doc2Vec(
    vector_size=300,     
    window=5,          
    min_count=2,         
    workers=4,          
    epochs=40,        
    dm=1,  
    seed=42
)

model.build_vocab(tagged_data)
model.train(tagged_data, total_examples=model.corpus_count, epochs=model.epochs)

print("Generating embeddings...")
all_embeddings = np.array([model.dv[str(i)] for i in range(len(txt_files))], dtype=np.float32)
all_embeddings /= np.linalg.norm(all_embeddings, axis=1, keepdims=True)

faiss_index = faiss.IndexFlatIP(all_embeddings.shape[1])
faiss_index.add(all_embeddings)
faiss.write_index(faiss_index, "./data/resume_index_doc2vec1.faiss")

with open("./data/resume_index_mapping_doc2vec1.json", "w", encoding="utf-8") as f:
    json.dump(txt_files, f, ensure_ascii=False, indent=4)

model.save("./data/doc2vec_resume1.model")

print(f"✅ Doc2Vec embeddings created: {all_embeddings.shape}")

Preparing documents: 100%|██████████| 2549/2549 [00:02<00:00, 1245.70it/s]

Training Doc2Vec model...

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Generating embeddings...
✅ Doc2Vec embeddings created: (2549, 300)

## 5. job offer embedding

In [19]:
import pandas as pd

In [20]:
path ="./data/job_offer/datasets/ravindrasinghrana/job-description-dataset/versions/1/job_descriptions.csv"
print("Path to dataset files:", path)
df = pd.read_csv(path)
df = df.sample(100000)

fields_to_combine = [
    "Job Id", 
    "Job Title", 
    "Job Description", 
    "skills", 
    "Responsibilities",
    "location"]
df["combined_text"] = df[fields_to_combine].astype(str).agg(" ".join, axis=1)

Path to dataset files: ./data/job_offer/datasets/ravindrasinghrana/job-description-dataset/versions/1/job_descriptions.csv

In [21]:
df.head()

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile,combined_text
787450,1628096998513522,0 to 14 Years,B.Tech,$55K-$92K,Phnom Penh,Cambodia,12.5657,104.9909,Part-Time,27523,...,Landscape Architect,Residential Landscape Designer,USAJOBS,Create aesthetically pleasing and functional l...,"{'Legal Assistance, Bonuses and Incentive Prog...",Landscape design Plant selection and care Hard...,Specialize in designing residential outdoor sp...,CSX,"{""Sector"":""Transportation"",""Industry"":""Railroa...",1628096998513522 Landscape Architect Create ae...
1177962,527104154159677,5 to 11 Years,M.Tech,$62K-$98K,Phnom Penh,Cambodia,12.5657,104.9909,Part-Time,125530,...,Software Architect,Solution Architect,USAJOBS,A Solution Architect designs and develops effe...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Solution design Technical architecture Cloud c...,Design high-level solution architectures for s...,IBM (International Business Machines Corporation),"{""Sector"":""Technology/IT Services"",""Industry"":...",527104154159677 Software Architect A Solution ...
661430,396281146091559,4 to 12 Years,MCA,$56K-$115K,Warsaw,Poland,51.9194,19.1451,Temporary,18575,...,Systems Engineer,Systems Integration Specialist,Idealist,The role of a Systems Integration Specialist i...,"{'Employee Referral Programs, Financial Counse...",Systems integration Integration architecture D...,Integrate various software and hardware system...,Leidos Holdings,"{""Sector"":""IT Services"",""Industry"":""Informatio...",396281146091559 Systems Engineer The role of a...
1277930,310287488169380,1 to 15 Years,B.Tech,$63K-$106K,Bamako,Mali,17.5707,-3.9962,Part-Time,123329,...,Psychologist,Clinical Psychologist,CareerBuilder,Clinical Psychologists diagnose and treat ment...,"{'Employee Assistance Programs (EAP), Tuition ...",Clinical psychology Counseling skills Assessme...,Provide therapy and counseling services to ind...,Seaboard,"{""Sector"":""Transportation"",""Industry"":""Food Pr...",310287488169380 Psychologist Clinical Psycholo...
1387246,1358975344563112,0 to 10 Years,B.Tech,$60K-$85K,Andorra la Vella,Andorra,42.5063,1.5218,Part-Time,68599,...,SEO Specialist,Content SEO Strategist,SimplyHired,Content SEO Strategists create SEO strategies ...,"{'Employee Referral Programs, Financial Counse...",Content strategy SEO content optimization Cont...,"Develop content strategies for SEO, including ...",Alcoa,"{""Sector"":""Metals"",""Industry"":""Metals"",""City"":...",1358975344563112 SEO Specialist Content SEO St...

In [22]:
df.columns

Index(['Job Id', 'Experience', 'Qualifications', 'Salary Range', 'location',
       'Country', 'latitude', 'longitude', 'Work Type', 'Company Size',
       'Job Posting Date', 'Preference', 'Contact Person', 'Contact',
       'Job Title', 'Role', 'Job Portal', 'Job Description', 'Benefits',
       'skills', 'Responsibilities', 'Company', 'Company Profile',
       'combined_text'],
      dtype='object')

### Embedding with SentenceTransformer

In [23]:
model = SentenceTransformer("all-MiniLM-L6-v2")
job_embeddings = model.encode(df["combined_text"].tolist(), convert_to_numpy=True, show_progress_bar=True, normalize_embeddings=True)

faiss_index = faiss.IndexFlatIP(job_embeddings.shape[1])
faiss_index.add(job_embeddings)
faiss.write_index(faiss_index, "./data/jobs_index.faiss")

job_id_mapping = {i: jid for i, jid in enumerate(df["Job Id"].tolist())}
with open("./data/jobs_index_mapping.json", "w", encoding="utf-8") as f:
    json.dump(job_id_mapping, f, indent=4)

Batches:   0%|          | 0/3125 [00:00<?, ?it/s]

### Embedding with Doc2vec

In [24]:
tagged_data = []
job_texts = df["combined_text"].tolist()

for idx, text in enumerate(tqdm(job_texts, desc="Preparing job documents")):
    tokens = simple_preprocess(str(text))
    tagged_data.append(TaggedDocument(words=tokens, tags=[str(idx)]))

print("Training Doc2Vec model for jobs...")
model = Doc2Vec(
    vector_size=300,
    window=5,
    min_count=2,
    workers=4,
    epochs=40,
    dm=1,
    seed=42
)

model.build_vocab(tagged_data)
model.train(tagged_data, total_examples=model.corpus_count, epochs=model.epochs)

print("Generating job embeddings...")
job_embeddings = np.array([model.dv[str(i)] for i in range(len(job_texts))], dtype=np.float32)
job_embeddings /= np.linalg.norm(job_embeddings, axis=1, keepdims=True)
faiss_index = faiss.IndexFlatIP(job_embeddings.shape[1])
faiss_index.add(job_embeddings)
faiss.write_index(faiss_index, "./data/jobs_index_doc2vec.faiss")

job_id_mapping = {i: jid for i, jid in enumerate(df["Job Id"].tolist())}
with open("./data/jobs_index_mapping_doc2vec.json", "w", encoding="utf-8") as f:
    json.dump(job_id_mapping, f, indent=4)

model.save("./data/doc2vec_jobs.model")

print(f"✅ Doc2Vec job embeddings created: {job_embeddings.shape}")

Preparing job documents: 100%|██████████| 100000/100000 [00:08<00:00, 11342.53it/s]

Training Doc2Vec model for jobs...

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Generating job embeddings...
✅ Doc2Vec job embeddings created: (100000, 300)

## 6. resume and job offer match

In [25]:
import umap.umap_ as umap
import matplotlib.pyplot as plt

In [26]:
CV_INDEX = [np.random.choice(2549) for _ in range(20)]
TOP_N = 2

### Matching with smaller embedded resume text

Matching with SentenceTransformer embedding

In [27]:
jobs_index = faiss.read_index("./data/jobs_index.faiss")
with open("./data/jobs_index_mapping.json", "r") as f:
    jobs_mapping = {int(k): v for k, v in json.load(f).items()}

resume_index = faiss.read_index("./data/resume_index.faiss")
with open("./data/resume_index_mapping.json", "r") as f:
    resume_mapping = json.load(f)

model = SentenceTransformer("all-MiniLM-L6-v2")

def reconstruct_embeddings(index):
    embeddings = np.zeros((index.ntotal, index.d), dtype=np.float32)
    for i in range(index.ntotal):
        index.reconstruct(i, embeddings[i])
    return embeddings

resume_json_folder = "./data/resume_extract_text"
resume_data = {}

for fname in os.listdir(resume_json_folder):
    if fname.lower().endswith(".txt"):
        path = os.path.join(resume_json_folder, fname)
        with open(path, "r", encoding="utf-8") as f:
            data = f.read()
        resume_data[fname] = data

jobs_df = pd.read_csv("./data/job_offer/datasets/ravindrasinghrana/job-description-dataset/versions/1/job_descriptions.csv")

cv_embeddings = reconstruct_embeddings(resume_index)
job_embeddings = reconstruct_embeddings(jobs_index)
all_embeddings = np.vstack([cv_embeddings, job_embeddings])
results_ST_small=[]

for cv_index in CV_INDEX:
    cv_filename = resume_mapping[cv_index]

    print("\n===== Selected resume =====")
    if cv_filename in resume_data:
        print(resume_data[cv_filename])

    cv_emb = cv_embeddings[cv_index:cv_index+1]
    distances, indices = jobs_index.search(cv_emb, TOP_N)

    results = [
        {"job_index": int(idx), "job_id": jobs_mapping[int(idx)], "score": float(score)}
        for score, idx in zip(distances[0], indices[0])
    ]

    print(f"\n===== Top {TOP_N} matching job offers =====")
    tmp_score=0
    for r in results:
        job_id = r["job_id"]
        tmp_score+=r['score']
        print(f"\n--- 💼 Found offers : {job_id} ---")
        print(f"Similarity score : {r['score']:.4f}")
        
        job_row = jobs_df[jobs_df["Job Id"] == job_id]

        if len(job_row) == 0:
            print("⚠️ Offer not found in jobs_df")
            continue
        
        row = job_row.iloc[0]
        
        fields_to_show = [
            "Job Title", "Company Name", "Location", "Experience",
            "Qualifications", "Skills", "Job Description", "Responsibilities",
            "Work Type", "Salary Range"
        ]
        
        for col in fields_to_show:
            if col in row and not pd.isna(row[col]):
                print(f"{col}: {row[col]}")
    results_ST_small.append(tmp_score/TOP_N)

===== Selected resume =====
Skills: classroom management; teaching; tutoring; counseling; experience with special needs; parent communication; interactive teaching/learning; innovative lesson planning; team building and leadership; lesson planning; education strategies; plan development; reading assistance; bilingual English/Spanish; teamwork; attention to detail; planning and organizing; multitasking; clear writing; active listening; feedback and collaboration; CPR/First Aid certified
Experience: Lead Teacher at Company Name; Head Teacher at Company Name; case manager at Company Name; Assistant Teacher at Company Name
Education: M.S. in Education/ Special Education Early childhood at Touro College; A.S., Liberal arts at Kingsborough Community College; Bachelor of Science in Psychology at College of Staten Island
Certifications: CPR; First Aid
Summary: Solid background in special needs and early childhood education, with strong emphasis in children's development. Consistently exceed teaching goals and parents expectations. Experienced in assessing and evaluating individual needs to provide an enhanced learning experience. Skilled in developing and implementing strategies and procedures.Enthusiastic teacher who has earned trust and respect from students, colleagues and administration for 12+ years.

===== Top 2 matching job offers =====

--- 💼 Found offers : 1805801453556571 ---
Similarity score : 0.5970
Job Title: Social Worker
Experience: 5 to 13 Years
Qualifications: M.Tech
Job Description: Work with at-risk children and families, assess needs, provide support, and ensure child safety and well-being.
Responsibilities: Provide support and counseling to children and families in need. Assess child safety and risk factors. Develop and implement care plans and interventions.
Work Type: Contract
Salary Range: $59K-$105K

--- 💼 Found offers : 3007208203205144 ---
Similarity score : 0.5959
Job Title: Social Worker
Experience: 5 to 10 Years
Qualifications: BA
Job Description: Work with at-risk children and families, assess needs, provide support, and ensure child safety and well-being.
Responsibilities: Provide support and counseling to children and families in need. Assess child safety and risk factors. Develop and implement care plans and interventions.
Work Type: Part-Time
Salary Range: $62K-$102K

===== Selected resume =====
Skills: Team Leading; English; Planning; Russian; French; Hebrew; Sales; Negotiations; Analytics; MS Office; BI Tools; SQL; PostgreSQL; Python; Airflow; Hadoop; Kafka; Vertica; Tableau; Power BI; PowerPoint; SAP
Experience: Analytics Lead / Competitive Analytics Team Lead at OZON; Category Business Manager at Samsung; Product Manager at Nikon
Education: MBA (Sales & Marketing) at IBDA, Moscow; Masters in Psychology at Moscow State University
Summary: Analytics leader with over a decade of experience building and leading analytics teams, delivering pricing, promotions, competitive intelligence and assortment insights to drive GMV and profitability. Proficient in SQL/Python/ETL tools and BI platforms (Tableau, Power BI) with a track record of presenting to C-level executives and executing from scratch to full deployment.

===== Top 2 matching job offers =====

--- 💼 Found offers : 2589223419813075 ---
Similarity score : 0.6212
Job Title: Data Analyst
Experience: 5 to 14 Years
Qualifications: B.Com
Job Description: Business Intelligence Analysts gather and analyze data to provide valuable insights to support decision-making within an organization. They create reports, dashboards, and data visualizations to help stakeholders understand trends, patterns, and opportunities in the data.
Responsibilities: Gather and analyze data to provide insights for decision-making using tools like Tableau or Power BI. Create data visualizations and reports. Identify trends and patterns in data.
Work Type: Part-Time
Salary Range: $63K-$95K

--- 💼 Found offers : 1882864670424246 ---
Similarity score : 0.6207
Job Title: Data Analyst
Experience: 4 to 14 Years
Qualifications: MCA
Job Description: Business Intelligence Analysts gather and analyze data to provide valuable insights to support decision-making within an organization. They create reports, dashboards, and data visualizations to help stakeholders understand trends, patterns, and opportunities in the data.
Responsibilities: Gather and analyze data to provide insights for decision-making using tools like Tableau or Power BI. Create data visualizations and reports. Identify trends and patterns in data.
Work Type: Temporary
Salary Range: $57K-$111K

===== Selected resume =====
Skills: account reconciliations; accounting system; accounts payable; process payroll; spreadsheets
Experience: Accountant at Company Name, City, State; Office Assistant at Company Name, City, State; Assistant at Company Name, City, State
Education: Master of Science in Accounting at Texas A&M Commerce; Bachelor of Business Administration in Accounting at Baylor University

===== Top 2 matching job offers =====

--- 💼 Found offers : 2018596011345325 ---
Similarity score : 0.5750
Job Title: Accountant
Experience: 5 to 12 Years
Qualifications: PhD
Job Description: Financial Accountants handle financial records, prepare financial statements, and ensure compliance with accounting standards. They analyze financial data to provide accurate financial reports and support decision-making within the organization.
Responsibilities: Maintain financial records, prepare financial statements, and ensure compliance with accounting standards and regulations. Reconcile accounts and analyze financial data. Assist with financial audits.
Work Type: Full-Time
Salary Range: $62K-$82K

--- 💼 Found offers : 401691087019389 ---
Similarity score : 0.5690
Job Title: Accountant
Experience: 0 to 9 Years
Qualifications: PhD
Job Description: Financial Accountants handle financial records, prepare financial statements, and ensure compliance with accounting standards. They analyze financial data to provide accurate financial reports and support decision-making within the organization.
Responsibilities: Maintain financial records, prepare financial statements, and ensure compliance with accounting standards and regulations. Reconcile accounts and analyze financial data. Assist with financial audits.
Work Type: Part-Time
Salary Range: $60K-$129K

===== Selected resume =====
Skills: ADP; Benefits; budget; databases; employee relations; special events; senior management; General Manager; hiring; HRIS; insurance; Kronos; labor relations; Lawson; leadership; managing; Medical Manager; meetings; Access; Excel; MS Office; Outlook; PowerPoint; Word; newsletter; Oracle; organizational development; payroll; PeopleSoft; performance reviews; personnel; policies; Progress; QuickBooks; record keeping; recruiting; reporting; retail; safety; teamwork; troubleshoot; 2000
Experience: Sr. HR Generalist at Company Name; Office Manager at Company Name; HR Specialist at Company Name
Education: Master of Science in Industrial/Organization Psychology at University of Phoenix; Bachelor of Arts in Business Administration (Human Resources Management) at InterAmerican University of Puerto Rico
Certifications: Certified Mouth Swab- Drug test facilitator
Summary: Quality-driven analytical professional who delivers consistent and successful results in HR affairs, including recruitment and retention, staff development, safety and health, mediation, conflict resolution, benefits and compensation, HR audit and records management, HR policies development and legal compliance. Highlights HRIS (Kronos, Lawson, PeopleSoft, QuickBooks, HBI, ADP & Oracle) MS Office (Word, Excel, PowerPoint, Access, Outlook), EMR, Medical Manager. Certified Mouth Swab- Drug test facilitator Accomplishments Created and implemented a training program for managers and supervisors including topics such as; employee motivation, effective leadership, completing disciplinary actions and performance reviews. Satisfied record keeping requirements evaluated during annual HR Audit. Reduce turnover rate by improving recruitment strategies, effective interviewing and proper selection. Improve employee relations events increasing employee participation and satisfaction

===== Top 2 matching job offers =====

--- 💼 Found offers : 354102462644860 ---
Similarity score : 0.5186
Job Title: Human Resources Manager
Experience: 4 to 10 Years
Qualifications: BBA
Job Description: HR Generalists handle various HR functions, including recruitment, employee relations, benefits administration, and HR compliance. They serve as a resource for employees and management, ensuring HR policies and practices align with organizational goals and legal requirements.
Responsibilities: Oversee various HR functions, including recruitment, benefits administration, and employee relations. Develop and implement HR policies and procedures. Handle employee inquiries and concerns.
Work Type: Contract
Salary Range: $59K-$109K

--- 💼 Found offers : 2492678088022865 ---
Similarity score : 0.5141
Job Title: Human Resources Manager
Experience: 3 to 10 Years
Qualifications: BBA
Job Description: HR Generalists handle various HR functions, including recruitment, employee relations, benefits administration, and HR compliance. They serve as a resource for employees and management, ensuring HR policies and practices align with organizational goals and legal requirements.
Responsibilities: Oversee various HR functions, including recruitment, benefits administration, and employee relations. Develop and implement HR policies and procedures. Handle employee inquiries and concerns.
Work Type: Intern
Salary Range: $64K-$113K

===== Selected resume =====
Skills: Training and development; Employee relations; Compensation administration; Performance management strategies; Human resources audits; Maintains confidentiality; HRMS; National Human Resources Association; Homeowners insurance knowledge; Excellent communicator; Deadline-driven; Marketing and sales specialist; New program and promotion implementation; Procedure development; Human Resources Information Systems (HRIS)
Experience: Consultant at Company Name; Loan Consultant / Developer at Company Name; Process Lead at Company Name; International Human Resource Manager at Company Name; Real Estate - Inspector at Company Name
Education: Professional in Human Resources (PHR) Certificate at Rice University / Susan B Glasscock; Mortgage Certification at Champions School of Real Estate; Bachelor of Science, Civil (Environmental) Engineering at Rutgers University
Certifications: Professional in Human Resources (PHR) Certificate; Mortgage Certification
Summary: CONSULTANT Career Focus Business Professional acutely focused on customer service and network building. Promptly develops vital relationships needed to operate and succeed in a sales field. Manager with expertise in delivering support services and resolving customer complaints. Over seven years of experience in Real estate development. Also a quick study, with an ability to easily grasp and put into application new ideas, concepts, and technologies. Exceptional organizational, communication, interpersonal, analytical, and problem resolution skills. Thrive in both independent and collaborative work environments. Proficient in the use of computer applications including MS Word, Excel, PowerPoint and Access, as well as AutoCAD and ACT.

===== Top 2 matching job offers =====

--- 💼 Found offers : 387078834036643 ---
Similarity score : 0.5451
Job Title: HR Manager
Experience: 2 to 9 Years
Qualifications: PhD
Job Description: A Human Resources Director leads HR functions, including talent acquisition, employee development, and HR strategy, to promote a positive work environment and support organizational goals.
Responsibilities: Oversee all HR functions, including recruitment, benefits administration, employee relations, and policy development. Align HR strategies with business goals. Provide leadership to the HR team.
Work Type: Full-Time
Salary Range: $56K-$111K

--- 💼 Found offers : 1314282053705754 ---
Similarity score : 0.5448
Job Title: HR Manager
Experience: 2 to 10 Years
Qualifications: B.Tech
Job Description: A Human Resources Director leads HR functions, including talent acquisition, employee development, and HR strategy, to promote a positive work environment and support organizational goals.
Responsibilities: Oversee all HR functions, including recruitment, benefits administration, employee relations, and policy development. Align HR strategies with business goals. Provide leadership to the HR team.
Work Type: Part-Time
Salary Range: $61K-$112K

===== Selected resume =====
Skills: administrative; administrative support; agency; budgets; conferences; contracts; counseling; clients; data collection; data management; data base; database; delivery; Department of Health; DOH; dialysis; staff training; expense reports; filing; grant applications; grant proposal; graphs; help-desk; Human Resource; Lexis Nexis; logistics; MAC; Director; managing; meetings; access; Excel; Outlook; PowerPoint; MS Windows; Word; policies; presentations; Procurement; progress; proposal; Public Speaking; Quality Assurance; Rehabilitation; reporting; Risk Management; sales; spreadsheets; technical support; phone; trade shows; travel arrangements; Soarian; MediNotes EMR
Experience: Coordinating Manager at Company Name; Executive Assistant at Company Name; Program Associate at Company Name; Sales Executive at Company Name
Education: Bachelor of Arts in Communications at The College Of New Rochelle
Certifications: Dale Carnegie Course - Public Speaking, Effective Communication and Human Relation; NYS Notary Public; American Heart Association Basic Life Support
Summary: COORDINATING MANAGER Summary Administrative Operations: Special events, meeting, and travel logistics; correspondence, file, records, and database management; project administration and executive-level management • Sales Support: Client service, accounts management, problem trouble-shooting and resolution; contract administration, order review, and shipping management; sales tracking and reporting • Communications: Business writer, proofreader, and editor; knowledgeable in medical terminology, policies and standards such as HIPAA • Financial/Budget Administration: Budget oversight, invoice verification, requisitions, expense tracking; purchasing, supply, and inventory management.

===== Top 2 matching job offers =====

--- 💼 Found offers : 2485180184354680 ---
Similarity score : 0.4645
Job Title: Administrative Assistant
Experience: 3 to 13 Years
Qualifications: M.Com
Job Description: Support high-level executives by managing schedules, coordinating meetings, and handling various administrative tasks.
Responsibilities: Provide high-level administrative support to executives, including managing schedules and communications. Coordinate meetings and travel arrangements. Handle confidential information with discretion.
Work Type: Full-Time
Salary Range: $64K-$98K

--- 💼 Found offers : 1808205248945064 ---
Similarity score : 0.4619
Job Title: Administrative Assistant
Experience: 0 to 8 Years
Qualifications: B.Com
Job Description: Support high-level executives by managing schedules, coordinating meetings, and handling various administrative tasks.
Responsibilities: Provide high-level administrative support to executives, including managing schedules and communications. Coordinate meetings and travel arrangements. Handle confidential information with discretion.
Work Type: Intern
Salary Range: $55K-$128K

===== Selected resume =====
Skills: Global Operations Management; Personnel Management; AutoCAD v.14/2008/2010; Budgeting, Planning, Forecasting; Training & Staff Development; Six Sigma; Vendor Kanban Contracts; Lean Manufacturing; AutoCAD Inventor 2010; Product Cost Reduction; Team Leadership/Team Building; Bosch/Item Software; New Product Development; Organization/Time Management; ANSI Drawing Standards; Inventory Control/Cycle Counts; Total Quality Management; Mechanical Design; Project Management; Customer Service; MS Office Suite; ROI Analyzes; Safety/Security; Virtual Gibbs; assembly; AutoCAD; automation; budgets; budget; CNC; electronics; layout; machine tools; machinery; market; materials; mathematics; mechanical; networks; packaging; PLC; policies; presentations; programming; quality; recording; sales; spreadsheet; team work
Experience: Engineering Manager/Senior Mechanical Designer at Company Name City, State; Plant Manager/Project Manager at Company Name City, State; Precision Machinist at Company Name City, State
Education: AutoCad at Penn State; General Diploma at Faith Christian Academy
Summary: Executive Summary Operations and Manufacturing Engineering Manager with more than 12 years of experience in high-volume global operations, support of automated production equipment and the design, layout and support of custom machinery. Proven record of leading multi-skilled teams to drive projects from pre-development through post-development cycle. Increased operational profitability by enhancing processes. Visionary, forward- looking, and pioneering with a passion for challenging projects. Leadership style is highly results-oriented.

===== Top 2 matching job offers =====

--- 💼 Found offers : 2101253646518216 ---
Similarity score : 0.6302
Job Title: Mechanical Engineer
Experience: 4 to 13 Years
Qualifications: B.Com
Job Description: Manufacturing Engineers optimize manufacturing processes, improve production efficiency, and ensure product quality in manufacturing environments.
Responsibilities: Improve manufacturing processes and production efficiency. Collaborate with production teams to implement lean manufacturing principles. Optimize manufacturing workflows and quality control.
Work Type: Contract
Salary Range: $56K-$120K

--- 💼 Found offers : 512466717251470 ---
Similarity score : 0.6287
Job Title: Mechanical Engineer
Experience: 3 to 8 Years
Qualifications: MBA
Job Description: Manufacturing Engineers optimize manufacturing processes, improve production efficiency, and ensure product quality in manufacturing environments.
Responsibilities: Improve manufacturing processes and production efficiency. Collaborate with production teams to implement lean manufacturing principles. Optimize manufacturing workflows and quality control.
Work Type: Contract
Salary Range: $59K-$92K

===== Selected resume =====
Skills: Communication skills; Creative problem solving; MS Windows; Quick learner; Trusted key holder; Sales; Phone; Publisher
Experience: Sales Advisor at Company Name; Cardiac Care Assistant at Company Name; Analyst at Company Name
Education: Bachelor's Degree in Biology at Dillard University
Summary: Motivated customer service specialist with over 30 years of retail experience in a fast-paced, team-based environment. Core strengths include creative problem solving, MS Windows proficiency, quick learner, trusted key holder, and exceptional communication skills.

===== Top 2 matching job offers =====

--- 💼 Found offers : 7940111126974 ---
Similarity score : 0.4661
Job Title: Customer Success Manager
Experience: 2 to 12 Years
Qualifications: M.Tech
Job Description: An Onboarding Specialist helps new employees integrate into the company. They facilitate orientation, training, and ensure a smooth transition into their roles.
Responsibilities: Facilitate the onboarding process for new customers, ensuring a smooth transition. Educate clients on product features and best practices. Provide training and resources for successful adoption.
Work Type: Full-Time
Salary Range: $60K-$113K

--- 💼 Found offers : 1300746101930224 ---
Similarity score : 0.4628
Job Title: Customer Support Specialist
Experience: 3 to 11 Years
Qualifications: MCA

Matching with Doc2vec embedding

In [29]:
cv_doc2vec_model = Doc2Vec.load("./data/doc2vec_resume.model")
job_doc2vec_model = Doc2Vec.load("./data/doc2vec_jobs.model")

resume_index = faiss.read_index("./data/resume_index_doc2vec.faiss")
with open("./data/resume_index_mapping_doc2vec.json", "r") as f:
    resume_mapping = json.load(f)

jobs_index = faiss.read_index("./data/jobs_index_doc2vec.faiss")
with open("./data/jobs_index_mapping_doc2vec.json", "r") as f:
    jobs_mapping = {int(k): v for k, v in json.load(f).items()}

def reconstruct_embeddings(index):
    embeddings = np.zeros((index.ntotal, index.d), dtype=np.float32)
    for i in range(index.ntotal):
        index.reconstruct(i, embeddings[i])
    return embeddings

resume_json_folder = "./data/resume_extract_text"
resume_data = {}

for fname in os.listdir(resume_json_folder):
    if fname.lower().endswith(".txt"):
        path = os.path.join(resume_json_folder, fname)
        with open(path, "r", encoding="utf-8") as f:
            data = f.read()
        resume_data[fname] = data

jobs_df = pd.read_csv("./data/job_offer/datasets/ravindrasinghrana/job-description-dataset/versions/1/job_descriptions.csv")

cv_embeddings = reconstruct_embeddings(resume_index)
job_embeddings = reconstruct_embeddings(jobs_index)

all_embeddings = np.vstack([cv_embeddings, job_embeddings])
results_D2V_small=[]

for cv_index in CV_INDEX:
    cv_filename = resume_mapping[cv_index]

    print("\n===== Selected resume =====")
    if cv_filename in resume_data:
        print(resume_data[cv_filename])

    cv_emb = cv_embeddings[cv_index:cv_index+1]
    distances, indices = jobs_index.search(cv_emb, TOP_N)

    results = [
        {"job_index": int(idx), "job_id": jobs_mapping[int(idx)], "score": float(score)}
        for score, idx in zip(distances[0], indices[0])
    ]

    print(f"\n===== Top {TOP_N} matching job offers =====")
    tmp_score=0
    for r in results:
        job_id = r["job_id"]
        tmp_score+=r['score']
        print(f"\n--- 💼 Found offers : {job_id} ---")
        print(f"Similarity score : {r['score']:.4f}")
        
        job_row = jobs_df[jobs_df["Job Id"] == job_id]

        if len(job_row) == 0:
            print("⚠️ Offre not found in jobs_df")
            continue
        
        row = job_row.iloc[0]
        
        fields_to_show = [
            "Job Title", "Company Name", "Location", "Experience",
            "Qualifications", "Skills", "Job Description", "Responsibilities",
            "Work Type", "Salary Range"
        ]
        
        for col in fields_to_show:
            if col in row and not pd.isna(row[col]):
                print(f"{col}: {row[col]}")
    results_D2V_small.append(tmp_score/TOP_N)

===== Selected resume =====
Skills: classroom management; teaching; tutoring; counseling; experience with special needs; parent communication; interactive teaching/learning; innovative lesson planning; team building and leadership; lesson planning; education strategies; plan development; reading assistance; bilingual English/Spanish; teamwork; attention to detail; planning and organizing; multitasking; clear writing; active listening; feedback and collaboration; CPR/First Aid certified
Experience: Lead Teacher at Company Name; Head Teacher at Company Name; case manager at Company Name; Assistant Teacher at Company Name
Education: M.S. in Education/ Special Education Early childhood at Touro College; A.S., Liberal arts at Kingsborough Community College; Bachelor of Science in Psychology at College of Staten Island
Certifications: CPR; First Aid
Summary: Solid background in special needs and early childhood education, with strong emphasis in children's development. Consistently exceed teaching goals and parents expectations. Experienced in assessing and evaluating individual needs to provide an enhanced learning experience. Skilled in developing and implementing strategies and procedures.Enthusiastic teacher who has earned trust and respect from students, colleagues and administration for 12+ years.

===== Top 2 matching job offers =====

--- 💼 Found offers : 761244617270601 ---
Similarity score : 0.2137
Job Title: Operations Manager
Experience: 0 to 9 Years
Qualifications: B.Com
Job Description: Quality Control Managers establish and enforce quality standards within an organization. They develop quality control processes, perform inspections, and implement corrective actions to maintain product or service quality.
Responsibilities: Establish and enforce quality control standards and procedures. Conduct quality audits and inspections. Collaborate with production teams to address quality issues and implement improvements.
Work Type: Contract
Salary Range: $62K-$94K

--- 💼 Found offers : 2615622739096572 ---
Similarity score : 0.2049
Job Title: Environmental Consultant
Experience: 4 to 14 Years
Qualifications: M.Com
Job Description: Environmental Compliance Officers ensure that organizations adhere to environmental regulations and standards. They conduct audits, develop compliance programs, and oversee efforts to minimize environmental impact and maintain regulatory compliance.
Responsibilities: Ensure compliance with environmental laws and regulations. Conduct environmental assessments and audits. Develop and implement compliance strategies.
Work Type: Full-Time
Salary Range: $61K-$83K

===== Selected resume =====
Skills: Team Leading; English; Planning; Russian; French; Hebrew; Sales; Negotiations; Analytics; MS Office; BI Tools; SQL; PostgreSQL; Python; Airflow; Hadoop; Kafka; Vertica; Tableau; Power BI; PowerPoint; SAP
Experience: Analytics Lead / Competitive Analytics Team Lead at OZON; Category Business Manager at Samsung; Product Manager at Nikon
Education: MBA (Sales & Marketing) at IBDA, Moscow; Masters in Psychology at Moscow State University
Summary: Analytics leader with over a decade of experience building and leading analytics teams, delivering pricing, promotions, competitive intelligence and assortment insights to drive GMV and profitability. Proficient in SQL/Python/ETL tools and BI platforms (Tableau, Power BI) with a track record of presenting to C-level executives and executing from scratch to full deployment.

===== Top 2 matching job offers =====

--- 💼 Found offers : 597996129735403 ---
Similarity score : 0.2387
Job Title: Financial Analyst
Experience: 2 to 12 Years
Qualifications: B.Tech
Job Description: Investment Analysts analyze financial data and market trends to make informed investment recommendations. They research and assess investment opportunities, create financial models, and provide insights to guide investment decisions and portfolio management.
Responsibilities: Analyze financial data, research investment opportunities, and provide recommendations for investment decisions. Monitor financial markets and economic trends. Prepare investment reports and presentations.
Work Type: Contract
Salary Range: $57K-$129K

--- 💼 Found offers : 1141116414716902 ---
Similarity score : 0.2376
Job Title: Database Administrator
Experience: 4 to 15 Years
Qualifications: B.Com
Job Description: A Database Analyst examines and interprets data stored in databases. They generate reports, identify trends, and provide insights to support business decision-making.
Responsibilities: Analyze and interpret database performance data, identifying areas for improvement. Troubleshoot database issues and optimize query performance. Generate reports and insights from database data.
Work Type: Intern
Salary Range: $55K-$100K

===== Selected resume =====
Skills: account reconciliations; accounting system; accounts payable; process payroll; spreadsheets
Experience: Accountant at Company Name, City, State; Office Assistant at Company Name, City, State; Assistant at Company Name, City, State
Education: Master of Science in Accounting at Texas A&M Commerce; Bachelor of Business Administration in Accounting at Baylor University

===== Top 2 matching job offers =====

--- 💼 Found offers : 2819058053795020 ---
Similarity score : 0.1449
Job Title: Front-End Engineer
Experience: 5 to 11 Years
Qualifications: PhD
Job Description: UI/UX Front-End Developers focus on creating user-friendly and visually appealing interfaces for web and mobile applications. They work on user experience design, responsive layouts, and front-end development to optimize user interactions.
Responsibilities: Focus on user interface (UI) and user experience (UX) design, translating design mockups into functional web interfaces. Conduct usability testing and iterate on designs.
Work Type: Full-Time
Salary Range: $61K-$124K

--- 💼 Found offers : 2047857101065958 ---
Similarity score : 0.1420
Job Title: Data Analyst
Experience: 4 to 12 Years
Qualifications: M.Com
Job Description: Data Quality Analysts ensure the accuracy, completeness, and consistency of data within an organization. They develop and implement data quality standards, perform data validation, and identify and resolve data quality issues to maintain data integrity.
Responsibilities: Ensure data accuracy and quality by identifying and addressing data issues and anomalies. Establish data quality standards and processes. Collaborate with data stewards to improve data quality.
Work Type: Part-Time
Salary Range: $63K-$125K

===== Selected resume =====
Skills: ADP; Benefits; budget; databases; employee relations; special events; senior management; General Manager; hiring; HRIS; insurance; Kronos; labor relations; Lawson; leadership; managing; Medical Manager; meetings; Access; Excel; MS Office; Outlook; PowerPoint; Word; newsletter; Oracle; organizational development; payroll; PeopleSoft; performance reviews; personnel; policies; Progress; QuickBooks; record keeping; recruiting; reporting; retail; safety; teamwork; troubleshoot; 2000
Experience: Sr. HR Generalist at Company Name; Office Manager at Company Name; HR Specialist at Company Name
Education: Master of Science in Industrial/Organization Psychology at University of Phoenix; Bachelor of Arts in Business Administration (Human Resources Management) at InterAmerican University of Puerto Rico
Certifications: Certified Mouth Swab- Drug test facilitator
Summary: Quality-driven analytical professional who delivers consistent and successful results in HR affairs, including recruitment and retention, staff development, safety and health, mediation, conflict resolution, benefits and compensation, HR audit and records management, HR policies development and legal compliance. Highlights HRIS (Kronos, Lawson, PeopleSoft, QuickBooks, HBI, ADP & Oracle) MS Office (Word, Excel, PowerPoint, Access, Outlook), EMR, Medical Manager. Certified Mouth Swab- Drug test facilitator Accomplishments Created and implemented a training program for managers and supervisors including topics such as; employee motivation, effective leadership, completing disciplinary actions and performance reviews. Satisfied record keeping requirements evaluated during annual HR Audit. Reduce turnover rate by improving recruitment strategies, effective interviewing and proper selection. Improve employee relations events increasing employee participation and satisfaction

===== Top 2 matching job offers =====

--- 💼 Found offers : 2347701777895159 ---
Similarity score : 0.0836
Job Title: Systems Analyst
Experience: 4 to 15 Years
Qualifications: BBA
Job Description: An IT Analyst assesses and analyzes IT systems, identifying areas for improvement, implementing technology solutions, and providing technical support to users and departments.
Responsibilities: Analyze business systems, processes, and requirements to identify IT solutions. Develop system specifications and requirements documents. Collaborate with IT teams to implement solutions.
Work Type: Temporary
Salary Range: $56K-$95K

--- 💼 Found offers : 1510737044529776 ---
Similarity score : 0.0809
Job Title: Network Analyst
Experience: 5 to 11 Years
Qualifications: MBA
Job Description: Network Performance Analysts monitor and optimize network performance. They collect and analyze network data, identify issues, and implement solutions to enhance network speed, reliability, and efficiency.
Responsibilities: Analyze network performance data, identify bottlenecks and latency issues, and optimize network performance. Collaborate with network engineers to implement improvements.
Work Type: Full-Time
Salary Range: $57K-$94K

===== Selected resume =====
Skills: Training and development; Employee relations; Compensation administration; Performance management strategies; Human resources audits; Maintains confidentiality; HRMS; National Human Resources Association; Homeowners insurance knowledge; Excellent communicator; Deadline-driven; Marketing and sales specialist; New program and promotion implementation; Procedure development; Human Resources Information Systems (HRIS)
Experience: Consultant at Company Name; Loan Consultant / Developer at Company Name; Process Lead at Company Name; International Human Resource Manager at Company Name; Real Estate - Inspector at Company Name
Education: Professional in Human Resources (PHR) Certificate at Rice University / Susan B Glasscock; Mortgage Certification at Champions School of Real Estate; Bachelor of Science, Civil (Environmental) Engineering at Rutgers University
Certifications: Professional in Human Resources (PHR) Certificate; Mortgage Certification
Summary: CONSULTANT Career Focus Business Professional acutely focused on customer service and network building. Promptly develops vital relationships needed to operate and succeed in a sales field. Manager with expertise in delivering support services and resolving customer complaints. Over seven years of experience in Real estate development. Also a quick study, with an ability to easily grasp and put into application new ideas, concepts, and technologies. Exceptional organizational, communication, interpersonal, analytical, and problem resolution skills. Thrive in both independent and collaborative work environments. Proficient in the use of computer applications including MS Word, Excel, PowerPoint and Access, as well as AutoCAD and ACT.

===== Top 2 matching job offers =====

--- 💼 Found offers : 1938479499859245 ---
Similarity score : 0.1773
Job Title: Business Analyst
Experience: 3 to 14 Years
Qualifications: BCA
Job Description: Healthcare Business Analysts work in the healthcare industry, analyzing data and processes to improve healthcare delivery. They collaborate with healthcare professionals and IT teams to optimize systems and workflows.
Responsibilities: Work in the healthcare sector, analyzing healthcare data and processes to improve patient care and operational efficiency. Identify opportunities for process improvement and cost reduction. Collaborate with healthcare professionals and stakeholders.
Work Type: Part-Time
Salary Range: $64K-$118K

--- 💼 Found offers : 2210910421496538 ---
Similarity score : 0.1653
Job Title: Financial Analyst
Experience: 3 to 9 Years
Qualifications: M.Tech
Job Description: Financial Planners help clients achieve their financial goals by providing personalized financial advice and investment strategies. They assess clients financial situations, develop financial plans, and offer recommendations on savings, investments, and retirement planning.
Responsibilities: Assist clients with financial planning, investment strategies, and retirement planning. Conduct comprehensive financial assessments. Provide personalized financial advice and recommendations.
Work Type: Temporary
Salary Range: $65K-$91K

===== Selected resume =====
Skills: administrative; administrative support; agency; budgets; conferences; contracts; counseling; clients; data collection; data management; data base; database; delivery; Department of Health; DOH; dialysis; staff training; expense reports; filing; grant applications; grant proposal; graphs; help-desk; Human Resource; Lexis Nexis; logistics; MAC; Director; managing; meetings; access; Excel; Outlook; PowerPoint; MS Windows; Word; policies; presentations; Procurement; progress; proposal; Public Speaking; Quality Assurance; Rehabilitation; reporting; Risk Management; sales; spreadsheets; technical support; phone; trade shows; travel arrangements; Soarian; MediNotes EMR
Experience: Coordinating Manager at Company Name; Executive Assistant at Company Name; Program Associate at Company Name; Sales Executive at Company Name
Education: Bachelor of Arts in Communications at The College Of New Rochelle
Certifications: Dale Carnegie Course - Public Speaking, Effective Communication and Human Relation; NYS Notary Public; American Heart Association Basic Life Support
Summary: COORDINATING MANAGER Summary Administrative Operations: Special events, meeting, and travel logistics; correspondence, file, records, and database management; project administration and executive-level management • Sales Support: Client service, accounts management, problem trouble-shooting and resolution; contract administration, order review, and shipping management; sales tracking and reporting • Communications: Business writer, proofreader, and editor; knowledgeable in medical terminology, policies and standards such as HIPAA • Financial/Budget Administration: Budget oversight, invoice verification, requisitions, expense tracking; purchasing, supply, and inventory management.

===== Top 2 matching job offers =====

--- 💼 Found offers : 2184453343733188 ---
Similarity score : 0.1889
Job Title: Chemical Engineer
Experience: 1 to 15 Years
Qualifications: BA
Job Description: Monitor and maintain product quality standards, perform inspections, and implement quality control procedures.
Responsibilities: Focus on product quality assurance and testing. Develop quality control procedures and standards. Investigate and resolve quality issues.
Work Type: Full-Time
Salary Range: $60K-$81K

--- 💼 Found offers : 411813488666868 ---
Similarity score : 0.1666
Job Title: Chemical Engineer
Experience: 1 to 12 Years
Qualifications: B.Tech
Job Description: Monitor and maintain product quality standards, perform inspections, and implement quality control procedures.
Responsibilities: Focus on product quality assurance and testing. Develop quality control procedures and standards. Investigate and resolve quality issues.
Work Type: Full-Time
Salary Range: $55K-$114K

===== Selected resume =====
Skills: Global Operations Management; Personnel Management; AutoCAD v.14/2008/2010; Budgeting, Planning, Forecasting; Training & Staff Development; Six Sigma; Vendor Kanban Contracts; Lean Manufacturing; AutoCAD Inventor 2010; Product Cost Reduction; Team Leadership/Team Building; Bosch/Item Software; New Product Development; Organization/Time Management; ANSI Drawing Standards; Inventory Control/Cycle Counts; Total Quality Management; Mechanical Design; Project Management; Customer Service; MS Office Suite; ROI Analyzes; Safety/Security; Virtual Gibbs; assembly; AutoCAD; automation; budgets; budget; CNC; electronics; layout; machine tools; machinery; market; materials; mathematics; mechanical; networks; packaging; PLC; policies; presentations; programming; quality; recording; sales; spreadsheet; team work
Experience: Engineering Manager/Senior Mechanical Designer at Company Name City, State; Plant Manager/Project Manager at Company Name City, State; Precision Machinist at Company Name City, State
Education: AutoCad at Penn State; General Diploma at Faith Christian Academy
Summary: Executive Summary Operations and Manufacturing Engineering Manager with more than 12 years of experience in high-volume global operations, support of automated production equipment and the design, layout and support of custom machinery. Proven record of leading multi-skilled teams to drive projects from pre-development through post-development cycle. Increased operational profitability by enhancing processes. Visionary, forward- looking, and pioneering with a passion for challenging projects. Leadership style is highly results-oriented.

===== Top 2 matching job offers =====

--- 💼 Found offers : 41243100681560 ---
Similarity score : 0.2207
Job Title: Data Analyst
Experience: 2 to 9 Years
Qualifications: BA
Job Description: Data Quality Analysts ensure the accuracy, completeness, and consistency of data within an organization. They develop and implement data quality standards, perform data validation, and identify and resolve data quality issues to maintain data integrity.
Responsibilities: Ensure data accuracy and quality by identifying and addressing data issues and anomalies. Establish data quality standards and processes. Collaborate with data stewards to improve data quality.
Work Type: Full-Time
Salary Range: $61K-$117K

--- 💼 Found offers : 1119511282991178 ---
Similarity score : 0.2141
Job Title: SEM Specialist
Experience: 0 to 9 Years
Qualifications: B.Tech
Job Description: SEM Analysts analyze search engine marketing (SEM) campaigns. They monitor performance, optimize keyword strategies, and provide insights to improve the effectiveness of SEM efforts.
Responsibilities: Analyze SEM data and trends to optimize campaigns and ad spend. Generate reports and insights to improve SEM strategies. Stay up-to-date with SEM industry changes and best practices.
Work Type: Full-Time
Salary Range: $59K-$123K

===== Selected resume =====
Skills: Communication skills; Creative problem solving; MS Windows; Quick learner; Trusted key holder; Sales; Phone; Publisher
Experience: Sales Advisor at Company Name; Cardiac Care Assistant at Company Name; Analyst at Company Name
Education: Bachelor's Degree in Biology at Dillard University
Summary: Motivated customer service specialist with over 30 years of retail experience in a fast-paced, team-based environment. Core strengths include creative problem solving, MS Windows proficiency, quick learner, trusted key holder, and exceptional communication skills.

===== Top 2 matching job offers =====

--- 💼 Found offers : 1609708312661183 ---
Similarity score : 0.2242
Job Title: Account Director
Experience: 2 to 13 Years
Qualifications: M.Tech
Job Description: Business Development Directors lead efforts to identify and pursue new business opportunities. They develop growth strategies, build relationships with clients, and oversee business development teams to achieve revenue and expansion goals.
Responsibilities: Develop and execute business development strategies to acquire new clients and grow accounts. Identify market opportunities and trends. Lead sales pitches and presentations.
Work Type: Temporary
Salary Range: $63K-$97K

--- 💼 Found offers : 2770340118772394 ---
Similarity score : 0.2161
Job Title: Finance Manager
Experience: 5 to 10 Years

### Matching with bigger embedded resume text

Matching with SentenceTransformer embedding

In [30]:
jobs_index = faiss.read_index("./data/jobs_index.faiss")
with open("./data/jobs_index_mapping.json", "r") as f:
    jobs_mapping = {int(k): v for k, v in json.load(f).items()}

resume_index = faiss.read_index("./data/resume_index1.faiss")
with open("./data/resume_index_mapping1.json", "r") as f:
    resume_mapping = json.load(f)

model = SentenceTransformer("all-MiniLM-L6-v2")

def reconstruct_embeddings(index):
    embeddings = np.zeros((index.ntotal, index.d), dtype=np.float32)
    for i in range(index.ntotal):
        index.reconstruct(i, embeddings[i])
    return embeddings

resume_json_folder = "./data/resume_extract_text1"
resume_data = {}

for fname in os.listdir(resume_json_folder):
    if fname.lower().endswith(".txt"):
        path = os.path.join(resume_json_folder, fname)
        with open(path, "r", encoding="utf-8") as f:
            data = f.read()
        resume_data[fname] = data

jobs_df = pd.read_csv("./data/job_offer/datasets/ravindrasinghrana/job-description-dataset/versions/1/job_descriptions.csv")

cv_embeddings = reconstruct_embeddings(resume_index)
job_embeddings = reconstruct_embeddings(jobs_index)
all_embeddings = np.vstack([cv_embeddings, job_embeddings])
results_ST_big=[]

for cv_index in CV_INDEX:
    cv_filename = resume_mapping[cv_index]

    print("\n===== Selected resume =====")
    if cv_filename in resume_data:
        print(resume_data[cv_filename])

    cv_emb = cv_embeddings[cv_index:cv_index+1]
    distances, indices = jobs_index.search(cv_emb, TOP_N)

    results = [
        {"job_index": int(idx), "job_id": jobs_mapping[int(idx)], "score": float(score)}
        for score, idx in zip(distances[0], indices[0])
    ]

    print(f"\n===== Top {TOP_N} matching job offers =====")
    tmp_score=0
    for r in results:
        job_id = r["job_id"]
        tmp_score+=r['score']
        print(f"\n--- 💼 Found offer : {job_id} ---")
        print(f"Similarity score : {r['score']:.4f}")
        
        job_row = jobs_df[jobs_df["Job Id"] == job_id]

        if len(job_row) == 0:
            print("⚠️ Offer not found in jobs_df")
            continue
        
        row = job_row.iloc[0]
        
        fields_to_show = [
            "Job Title", "Company Name", "Location", "Experience",
            "Qualifications", "Skills", "Job Description", "Responsibilities",
            "Work Type", "Salary Range"
        ]
        
        for col in fields_to_show:
            if col in row and not pd.isna(row[col]):
                print(f"{col}: {row[col]}")
    results_ST_big.append(tmp_score/TOP_N)

===== Selected resume =====
Skills: classroom management; teaching; tutoring; counseling; experience with special needs; parent communication; interactive teaching/learning; innovative lesson planning; team building and leadership; lesson planning; education strategies; plan development; reading assistance; bilingual English/Spanish; teamwork; attention to detail; planning and organizing; multitasking; clear writing; active listening; feedback and collaboration; CPR/First Aid certified
Experience: Lead Teacher at Company Name (Aug 2013 - Jun 2015) : Plan and execute daily lessons. Manage children portfolio and progress using Teaching Strategies Gold. Make in-home student referrals. Maintain the comfort, safety and educational demeanor of the classroom environment. Supervise one assistant teacher's in the classroom. Plan and allocate work equally among the staff. Evaluate and test students for appropriate class placement. | Head Teacher at Company Name (Jan 2003 - Aug 2013) : Evaluate and test students for appropriate class placement. Translate CPSE evaluations to non-English speaking parents. Collaborate with school administrators and parents to develop student program plans to ensure successful outcomes. Conduct family conference to discuss student progress, needs and referrals. Develop and enter daily observations, progress and attendance notes into school data base. Plan and execute daily lessons. Make in-home student referrals. Maintain the comfort, safety and educational demeanor of the classroom environment. Supervise three assistant teachers in the classroom. Plan and allocate work equally among the staff. | case manager at Company Name (Oct 2005 - May 2006) : Managed a caseload of over 18 at risk teenage and young adult females. Met with client's family members and drug counselors when substance abuse was issue in order to determine such activities and keep recidivism down. Helped clients with school enrollment and verified attendance. Held weekly team conferences to discuss client court dates, progress and concern in order to prepare monthly court reports for legal staff and judges. Provided case management services, escort, face to face services in community, communication with community providers, conducted site visits to shelter, residential and outpatient programs, and attending case conferences to engage and support participants in community treatment. Addressed any ongoing legal and or personal issues our female population was dealing with. Kept track of client progress via company database systems. Set up random drug tests in collaboration with our Substance Unit for female participants abuse. Directed any participant mental health concerns to our director. Made referrals for participants to outpatient/inpatient drug treatments facilities. Act as advocate and liaison for participants in securing access to community services, income support and self help | Assistant Teacher at Company Name (Jan 2001 - Jan 2003) : Collaborated with classroom assistants and teachers in creating weekly classroom lesson plans on a bi-weekly basis. Evaluated and tested students for appropriate class placement. Reviewed daily progress notes before they were entered into the company's electronic system and edited them as needed. Responsible for ordering, receiving and distributing office and classroom supplies.
Education: M.S. in Education/ Special Education Early childhood at Touro College; A.S., Liberal arts at Kingsborough Community College; Bachelor of Science in Psychology at College of Staten Island
Certifications: CPR; First Aid
Summary: Solid background in special needs and early childhood education, with strong emphasis in children's development. Consistently exceed teaching goals and parents expectations. Experienced in assessing and evaluating individual needs to provide an enhanced learning experience. Skilled in developing and implementing strategies and procedures.Enthusiastic teacher who has earned trust and respect from students, colleagues and administration for 12+ years.

===== Top 2 matching job offers =====

--- 💼 Found offer : 360233278989122 ---
Similarity score : 0.6129
Job Title: Teacher
Experience: 5 to 15 Years
Qualifications: B.Tech
Job Description: A Classroom Teacher educates students in a specific subject or grade level. They create lesson plans, deliver instruction, assess student progress, and foster a positive learning environment.
Responsibilities: Plan and deliver engaging lessons, adapting teaching methods to student needs. Assess student progress and provide feedback. Create a positive and inclusive classroom environment.
Work Type: Part-Time
Salary Range: $55K-$114K

--- 💼 Found offer : 1862833538845066 ---
Similarity score : 0.6118
Job Title: Teacher
Experience: 3 to 9 Years
Qualifications: M.Tech
Job Description: A Classroom Teacher educates students in a specific subject or grade level. They create lesson plans, deliver instruction, assess student progress, and foster a positive learning environment.
Responsibilities: Plan and deliver engaging lessons, adapting teaching methods to student needs. Assess student progress and provide feedback. Create a positive and inclusive classroom environment.
Work Type: Full-Time
Salary Range: $62K-$116K

===== Selected resume =====
Skills: Team Leading; English; Planning; Russian; French; Hebrew; Sales; Negotiations; Analytics; MS Office; BI Tools; SQL; PostgreSQL; Python; Airflow; Hadoop; Kafka; Vertica; Tableau; Power BI; PowerPoint; SAP
Experience: Analytics Lead / Competitive Analytics Team Lead at OZON (2022 - Present) : Leading a team of 18 analysts, delivering business insights for pricing, promotions, competitive activities and GMV. Presenting results to C-level executives using Tableau; building dashboards and data marts; end-to-end analytics from scratch. Proficient in SQL/PostgreSQL/Python/Airflow/Hadoop/Kafka/Vertica/Tableau/Power BI. | Category Business Manager at Samsung (2019 - 2022) : Development and execution strategy for Home Appliances in the CIS region. Managed sales structure, assortment, pricing, marketing, PLC and P&L. Grew category GMV and profit; introduced new product type (DW). | Product Manager at Nikon (2013 - 2019) : DSLR & Optics product management; #1 MS in DSLR/Optics and accessories sales strategy. Led Sport Optics development and promotions; product creation in collaboration with HQ.
Education: MBA (Sales & Marketing) at IBDA, Moscow; Masters in Psychology at Moscow State University
Summary: Analytics leader with over a decade of experience building and leading analytics teams, delivering pricing, promotions, competitive intelligence and assortment insights to drive GMV and profitability. Proficient in SQL/Python/ETL tools and BI platforms (Tableau, Power BI) with a track record of presenting to C-level executives and executing from scratch to full deployment.

===== Top 2 matching job offers =====

--- 💼 Found offer : 1580696507970253 ---
Similarity score : 0.6100
Job Title: Data Analyst
Experience: 0 to 14 Years
Qualifications: MCA
Job Description: Business Intelligence Analysts gather and analyze data to provide valuable insights to support decision-making within an organization. They create reports, dashboards, and data visualizations to help stakeholders understand trends, patterns, and opportunities in the data.
Responsibilities: Gather and analyze data to provide insights for decision-making using tools like Tableau or Power BI. Create data visualizations and reports. Identify trends and patterns in data.
Work Type: Part-Time
Salary Range: $64K-$122K

--- 💼 Found offer : 1665184751253682 ---
Similarity score : 0.6048
Job Title: Data Analyst
Experience: 3 to 11 Years
Qualifications: MBA
Job Description: Business Intelligence Analysts gather and analyze data to provide valuable insights to support decision-making within an organization. They create reports, dashboards, and data visualizations to help stakeholders understand trends, patterns, and opportunities in the data.
Responsibilities: Gather and analyze data to provide insights for decision-making using tools like Tableau or Power BI. Create data visualizations and reports. Identify trends and patterns in data.
Work Type: Temporary
Salary Range: $62K-$92K

===== Selected resume =====
Skills: account reconciliations; accounting system; accounts payable; process payroll; spreadsheets
Experience: Accountant at Company Name, City, State (2016-03 - 2018-03) : Reconcile bank accounts daily; process accounts payable; maintain general ledgers; create and modify existing Excel documents; maintain and process payroll; maintain accounting system; perform month-end procedures and account reconciliations; create and modify existing journal entries; perform accounting data reconciliations and verifications; prepare and file 1099s, 941s, 940s, W-2s, and C-3s; pay payroll taxes every pay period using EFTPS; roll over tax and fiscal years at year-end and perform all closing procedures; organize and prepare files for yearly audit. | Office Assistant at Company Name, City, State (2015-06 - 2015-08) : Answer phone; deliver mail; help professors maintain Excel documents; organize papers for professors. | Assistant at Company Name, City, State (2014-05 - 2014-08) : Maintain Excel spreadsheets.
Education: Master of Science in Accounting at Texas A&M Commerce; Bachelor of Business Administration in Accounting at Baylor University

===== Top 2 matching job offers =====

--- 💼 Found offer : 401691087019389 ---
Similarity score : 0.6042
Job Title: Accountant
Experience: 0 to 9 Years
Qualifications: PhD
Job Description: Financial Accountants handle financial records, prepare financial statements, and ensure compliance with accounting standards. They analyze financial data to provide accurate financial reports and support decision-making within the organization.
Responsibilities: Maintain financial records, prepare financial statements, and ensure compliance with accounting standards and regulations. Reconcile accounts and analyze financial data. Assist with financial audits.
Work Type: Part-Time
Salary Range: $60K-$129K

--- 💼 Found offer : 2018596011345325 ---
Similarity score : 0.5953
Job Title: Accountant
Experience: 5 to 12 Years
Qualifications: PhD
Job Description: Financial Accountants handle financial records, prepare financial statements, and ensure compliance with accounting standards. They analyze financial data to provide accurate financial reports and support decision-making within the organization.
Responsibilities: Maintain financial records, prepare financial statements, and ensure compliance with accounting standards and regulations. Reconcile accounts and analyze financial data. Assist with financial audits.
Work Type: Full-Time
Salary Range: $62K-$82K

===== Selected resume =====
Skills: ADP; Benefits; budget; databases; employee relations; special events; senior management; General Manager; hiring; HRIS; insurance; Kronos; labor relations; Lawson; leadership; managing; Medical Manager; meetings; Access; Excel; MS Office; Outlook; PowerPoint; Word; newsletter; Oracle; organizational development; payroll; PeopleSoft; performance reviews; personnel; policies; Progress; QuickBooks; record keeping; recruiting; reporting; retail; safety; teamwork; troubleshoot; 2000
Experience: Sr. HR Generalist at Company Name (01/2012 - Current) : Manage and Coordinate HR Support to 5 Resorts throughout South and Central Florida. Enforce company's policies and procedures for 2000+ employees, in conjunction with the bargaining agreement. Responsible for short and long term planning and management of the Human Resources function. Recommend the department's budget and manage expenses within approved budget constraints. Major areas of responsibility/management include, but are not limited to, employment, wage and salary administration, benefits, training, employee/labor relations, organizational development and payroll. Work closely with Resorts General Manager implementing, achieving and maintaining the Resort's goals and objectives. Participate in total Resort management as a member of the Resort Executive Team. Key Accomplishments: Created and implemented a training program for managers and supervisors including topics such as; employee motivation, effective leadership, completing disciplinary actions and performance reviews. Satisfied record keeping requirements evaluated during annual HR Audit. Reduce turnover rate by improving recruitment strategies, effective interviewing and proper selection. Improve employee relations events increasing employee participation and satisfaction. | Office Manager at Company Name (01/2010 - 01/2011) : Responsible for recruiting, interviewing, and hiring as well as monitoring payroll for over 60 retail employees. Managed workers compensation cases for all employees. Maintain HRIS database and 200+ personnel files. Conducted reference checks and performed new hire and safety orientation for new employees. Administer Personal Time Off and Sick Time records in the HRIS database for over 4000 employees in 4 states. Ran and audited weekly benefits reports. Acted as a liaison between benefit vendors and employees to resolve and troubleshoot claims issues. Issue monthly and quarterly workers compensation reports to senior management. Maintained OSHA logs and acted as a liaison between the carrier and the injured employees. Conducted new hire benefits orientation and organized annual benefits fair. Key Accomplishments: Developed and implemented PTO plans and Sick Time Plans for groups of employees that were currently not being tracked in the HRIS database. Discovered and corrected a $200,000 error in reporting reserves for workers compensation claims. Redesigned and updated the open enrollment and new hire benefits newsletter. Provide assistance to the Benefits Manager in creating a companywide wellness program. | HR Specialist at Company Name (01/2008 - 01/2010) : Promoted company wide a broad range of HR functions; Job Fairs and , administering benefits, overseeing disciplinary actions, and managing HR records. Co-chaired annual flex-enrollment meetings, resolved conflicts between employees and insurance carriers, coordinated health fairs to promote employee wellness and performed exit interviews. Worked with senior management to create HR policies and procedures; recruit employees; create group benefits databases; and develop orientation, training and incentive programs. Key Accomplishments: Foster a teamwork/open-door environment conducive to positive dialogue across the organization. Personal efforts were cited as the driving force behind branch's employee-retention rate of 89% within an industry where high turnover is the norm. Devise creative and cost-effective incentive and morale-boosting programs (including special events and a tiered awards structure) that increased employee satisfaction and productivity. Reduced benefits costs by 15% annually through meticulous recordkeeping and ensuring that company did not pay for benefits for which employees were ineligible.
Education: Master of Science in Industrial/Organization Psychology at University of Phoenix; Bachelor of Arts in Business Administration (Human Resources Management) at InterAmerican University of Puerto Rico
Certifications: Certified Mouth Swab- Drug test facilitator
Summary: Quality-driven analytical professional who delivers consistent and successful results in HR affairs, including recruitment and retention, staff development, safety and health, mediation, conflict resolution, benefits and compensation, HR audit and records management, HR policies development and legal compliance. Highlights HRIS (Kronos, Lawson, PeopleSoft, QuickBooks, HBI, ADP & Oracle) MS Office (Word, Excel, PowerPoint, Access, Outlook), EMR, Medical Manager. Certified Mouth Swab- Drug test facilitator Accomplishments Created and implemented a training program for managers and supervisors including topics such as; employee motivation, effective leadership, completing disciplinary actions and performance reviews. Satisfied record keeping requirements evaluated during annual HR Audit. Reduce turnover rate by improving recruitment strategies, effective interviewing and proper selection. Improve employee relations events increasing employee participation and satisfaction

===== Top 2 matching job offers =====

--- 💼 Found offer : 1766176254780163 ---
Similarity score : 0.6446
Job Title: Human Resources Manager
Experience: 0 to 10 Years
Qualifications: B.Tech
Job Description: HR Generalists handle various HR functions, including recruitment, employee relations, benefits administration, and HR compliance. They serve as a resource for employees and management, ensuring HR policies and practices align with organizational goals and legal requirements.
Responsibilities: Oversee various HR functions, including recruitment, benefits administration, and employee relations. Develop and implement HR policies and procedures. Handle employee inquiries and concerns.
Work Type: Full-Time
Salary Range: $60K-$127K

--- 💼 Found offer : 440090970227467 ---
Similarity score : 0.6441
Job Title: Human Resources Manager
Experience: 3 to 14 Years
Qualifications: PhD
Job Description: HR Generalists handle various HR functions, including recruitment, employee relations, benefits administration, and HR compliance. They serve as a resource for employees and management, ensuring HR policies and practices align with organizational goals and legal requirements.
Responsibilities: Oversee various HR functions, including recruitment, benefits administration, and employee relations. Develop and implement HR policies and procedures. Handle employee inquiries and concerns.
Work Type: Contract
Salary Range: $64K-$87K

===== Selected resume =====
Skills: Training and development; Employee relations; Compensation administration; Performance management strategies; Human resources audits; Maintains confidentiality; HRMS; National Human Resources Association; Homeowners insurance knowledge; Excellent communicator; Deadline-driven; Marketing and sales specialist; New program and promotion implementation; Procedure development; Human Resources Information Systems (HRIS)

Matching with Doc2vec embedding

In [31]:
cv_doc2vec_model = Doc2Vec.load("./data/doc2vec_resume1.model")
job_doc2vec_model = Doc2Vec.load("./data/doc2vec_jobs.model")

resume_index = faiss.read_index("./data/resume_index_doc2vec1.faiss")
with open("./data/resume_index_mapping_doc2vec1.json", "r") as f:
    resume_mapping = json.load(f)

jobs_index = faiss.read_index("./data/jobs_index_doc2vec.faiss")
with open("./data/jobs_index_mapping_doc2vec.json", "r") as f:
    jobs_mapping = {int(k): v for k, v in json.load(f).items()}

def reconstruct_embeddings(index):
    embeddings = np.zeros((index.ntotal, index.d), dtype=np.float32)
    for i in range(index.ntotal):
        index.reconstruct(i, embeddings[i])
    return embeddings

resume_json_folder = "./data/resume_extract_text1"
resume_data = {}

for fname in os.listdir(resume_json_folder):
    if fname.lower().endswith(".txt"):
        path = os.path.join(resume_json_folder, fname)
        with open(path, "r", encoding="utf-8") as f:
            data = f.read()
        resume_data[fname] = data

jobs_df = pd.read_csv("./data/job_offer/datasets/ravindrasinghrana/job-description-dataset/versions/1/job_descriptions.csv")

cv_embeddings = reconstruct_embeddings(resume_index)
job_embeddings = reconstruct_embeddings(jobs_index)

all_embeddings = np.vstack([cv_embeddings, job_embeddings])
results_D2V_big=[]

for cv_index in CV_INDEX:
    cv_filename = resume_mapping[cv_index]

    print("===== Selected resume =====")
    if cv_filename in resume_data:
        print(resume_data[cv_filename])

    cv_emb = cv_embeddings[cv_index:cv_index+1]

    distances, indices = jobs_index.search(cv_emb, TOP_N)

    results = [
        {"job_index": int(idx), "job_id": jobs_mapping[int(idx)], "score": float(score)}
        for score, idx in zip(distances[0], indices[0])
    ]

    print(f"\n===== Top {TOP_N} matching job offers =====")
    tmp_score=0
    for r in results:
        job_id = r["job_id"]
        tmp_score+=r['score']
        print(f"\n--- 💼 Found offers : {job_id} ---")
        print(f"Similarity score : {r['score']:.4f}")
        
        job_row = jobs_df[jobs_df["Job Id"] == job_id]

        if len(job_row) == 0:
            print("⚠️ Offre not found in jobs_df")
            continue
        
        row = job_row.iloc[0]
        
        fields_to_show = [
            "Job Title", "Company Name", "Location", "Experience",
            "Qualifications", "Skills", "Job Description", "Responsibilities",
            "Work Type", "Salary Range"
        ]
        
        for col in fields_to_show:
            if col in row and not pd.isna(row[col]):
                print(f"{col}: {row[col]}")
    results_D2V_big.append(tmp_score/TOP_N)

===== Selected resume =====
Skills: classroom management; teaching; tutoring; counseling; experience with special needs; parent communication; interactive teaching/learning; innovative lesson planning; team building and leadership; lesson planning; education strategies; plan development; reading assistance; bilingual English/Spanish; teamwork; attention to detail; planning and organizing; multitasking; clear writing; active listening; feedback and collaboration; CPR/First Aid certified
Experience: Lead Teacher at Company Name (Aug 2013 - Jun 2015) : Plan and execute daily lessons. Manage children portfolio and progress using Teaching Strategies Gold. Make in-home student referrals. Maintain the comfort, safety and educational demeanor of the classroom environment. Supervise one assistant teacher's in the classroom. Plan and allocate work equally among the staff. Evaluate and test students for appropriate class placement. | Head Teacher at Company Name (Jan 2003 - Aug 2013) : Evaluate and test students for appropriate class placement. Translate CPSE evaluations to non-English speaking parents. Collaborate with school administrators and parents to develop student program plans to ensure successful outcomes. Conduct family conference to discuss student progress, needs and referrals. Develop and enter daily observations, progress and attendance notes into school data base. Plan and execute daily lessons. Make in-home student referrals. Maintain the comfort, safety and educational demeanor of the classroom environment. Supervise three assistant teachers in the classroom. Plan and allocate work equally among the staff. | case manager at Company Name (Oct 2005 - May 2006) : Managed a caseload of over 18 at risk teenage and young adult females. Met with client's family members and drug counselors when substance abuse was issue in order to determine such activities and keep recidivism down. Helped clients with school enrollment and verified attendance. Held weekly team conferences to discuss client court dates, progress and concern in order to prepare monthly court reports for legal staff and judges. Provided case management services, escort, face to face services in community, communication with community providers, conducted site visits to shelter, residential and outpatient programs, and attending case conferences to engage and support participants in community treatment. Addressed any ongoing legal and or personal issues our female population was dealing with. Kept track of client progress via company database systems. Set up random drug tests in collaboration with our Substance Unit for female participants abuse. Directed any participant mental health concerns to our director. Made referrals for participants to outpatient/inpatient drug treatments facilities. Act as advocate and liaison for participants in securing access to community services, income support and self help | Assistant Teacher at Company Name (Jan 2001 - Jan 2003) : Collaborated with classroom assistants and teachers in creating weekly classroom lesson plans on a bi-weekly basis. Evaluated and tested students for appropriate class placement. Reviewed daily progress notes before they were entered into the company's electronic system and edited them as needed. Responsible for ordering, receiving and distributing office and classroom supplies.
Education: M.S. in Education/ Special Education Early childhood at Touro College; A.S., Liberal arts at Kingsborough Community College; Bachelor of Science in Psychology at College of Staten Island
Certifications: CPR; First Aid
Summary: Solid background in special needs and early childhood education, with strong emphasis in children's development. Consistently exceed teaching goals and parents expectations. Experienced in assessing and evaluating individual needs to provide an enhanced learning experience. Skilled in developing and implementing strategies and procedures.Enthusiastic teacher who has earned trust and respect from students, colleagues and administration for 12+ years.

===== Top 2 matching job offers =====

--- 💼 Found offers : 1789558942024253 ---
Similarity score : 0.1996
Job Title: Marketing Director
Experience: 0 to 12 Years
Qualifications: BA
Job Description: Digital Marketing Directors lead digital marketing efforts. They develop and execute digital strategies, oversee campaigns, and measure performance to achieve marketing goals.
Responsibilities: Develop and oversee digital marketing strategies, including SEO, SEM, and social media campaigns. Analyze digital marketing performance metrics. Manage digital marketing budgets.
Work Type: Intern
Salary Range: $55K-$124K

--- 💼 Found offers : 1122517028677491 ---
Similarity score : 0.1995
Job Title: Marketing Director
Experience: 4 to 9 Years
Qualifications: BCA
Job Description: Digital Marketing Directors lead digital marketing efforts. They develop and execute digital strategies, oversee campaigns, and measure performance to achieve marketing goals.
Responsibilities: Develop and oversee digital marketing strategies, including SEO, SEM, and social media campaigns. Analyze digital marketing performance metrics. Manage digital marketing budgets.
Work Type: Contract
Salary Range: $62K-$121K
===== Selected resume =====
Skills: Team Leading; English; Planning; Russian; French; Hebrew; Sales; Negotiations; Analytics; MS Office; BI Tools; SQL; PostgreSQL; Python; Airflow; Hadoop; Kafka; Vertica; Tableau; Power BI; PowerPoint; SAP
Experience: Analytics Lead / Competitive Analytics Team Lead at OZON (2022 - Present) : Leading a team of 18 analysts, delivering business insights for pricing, promotions, competitive activities and GMV. Presenting results to C-level executives using Tableau; building dashboards and data marts; end-to-end analytics from scratch. Proficient in SQL/PostgreSQL/Python/Airflow/Hadoop/Kafka/Vertica/Tableau/Power BI. | Category Business Manager at Samsung (2019 - 2022) : Development and execution strategy for Home Appliances in the CIS region. Managed sales structure, assortment, pricing, marketing, PLC and P&L. Grew category GMV and profit; introduced new product type (DW). | Product Manager at Nikon (2013 - 2019) : DSLR & Optics product management; #1 MS in DSLR/Optics and accessories sales strategy. Led Sport Optics development and promotions; product creation in collaboration with HQ.
Education: MBA (Sales & Marketing) at IBDA, Moscow; Masters in Psychology at Moscow State University
Summary: Analytics leader with over a decade of experience building and leading analytics teams, delivering pricing, promotions, competitive intelligence and assortment insights to drive GMV and profitability. Proficient in SQL/Python/ETL tools and BI platforms (Tableau, Power BI) with a track record of presenting to C-level executives and executing from scratch to full deployment.

===== Top 2 matching job offers =====

--- 💼 Found offers : 253274435030088 ---
Similarity score : 0.1554
Job Title: Java Developer
Experience: 1 to 9 Years
Qualifications: MCA
Job Description: Java Web Application Developers create web applications using Java technologies. They develop user interfaces, integrate backend systems, and ensure the functionality and security of web applications to provide a seamless user experience.
Responsibilities: Focus on developing Java-based web applications, including frontend and backend components. Create user interfaces and integrate with databases. Ensure web application security and performance.
Work Type: Contract
Salary Range: $56K-$86K

--- 💼 Found offers : 1555577612490120 ---
Similarity score : 0.1491
Job Title: Database Administrator
Experience: 0 to 12 Years
Qualifications: B.Tech
Job Description: A Database Analyst examines and interprets data stored in databases. They generate reports, identify trends, and provide insights to support business decision-making.
Responsibilities: Analyze and interpret database performance data, identifying areas for improvement. Troubleshoot database issues and optimize query performance. Generate reports and insights from database data.
Work Type: Contract
Salary Range: $65K-$89K
===== Selected resume =====
Skills: account reconciliations; accounting system; accounts payable; process payroll; spreadsheets
Experience: Accountant at Company Name, City, State (2016-03 - 2018-03) : Reconcile bank accounts daily; process accounts payable; maintain general ledgers; create and modify existing Excel documents; maintain and process payroll; maintain accounting system; perform month-end procedures and account reconciliations; create and modify existing journal entries; perform accounting data reconciliations and verifications; prepare and file 1099s, 941s, 940s, W-2s, and C-3s; pay payroll taxes every pay period using EFTPS; roll over tax and fiscal years at year-end and perform all closing procedures; organize and prepare files for yearly audit. | Office Assistant at Company Name, City, State (2015-06 - 2015-08) : Answer phone; deliver mail; help professors maintain Excel documents; organize papers for professors. | Assistant at Company Name, City, State (2014-05 - 2014-08) : Maintain Excel spreadsheets.
Education: Master of Science in Accounting at Texas A&M Commerce; Bachelor of Business Administration in Accounting at Baylor University

===== Top 2 matching job offers =====

--- 💼 Found offers : 1077655037505814 ---
Similarity score : 0.2172
Job Title: Marketing Analyst
Experience: 4 to 15 Years
Qualifications: M.Tech
Job Description: Analyze digital marketing campaigns, track performance metrics, and optimize online marketing strategies.
Responsibilities: Focus on digital marketing data analysis, including website traffic, SEO, and social media metrics. Optimize digital marketing campaigns based on data-driven insights. Report on digital marketing performance.
Work Type: Contract
Salary Range: $55K-$106K

--- 💼 Found offers : 3074128602337652 ---
Similarity score : 0.2093
Job Title: Business Analyst
Experience: 1 to 15 Years
Qualifications: MCA
Job Description: IT Business Analysts bridge the gap between business needs and technology solutions. They analyze business processes, gather requirements, and create solutions that align with organizational goals.
Responsibilities: Analyze business processes, gather requirements, and recommend solutions to enhance efficiency and productivity. Create business process models and documentation. Collaborate with IT teams to implement solutions.
Work Type: Temporary
Salary Range: $55K-$125K
===== Selected resume =====
Skills: ADP; Benefits; budget; databases; employee relations; special events; senior management; General Manager; hiring; HRIS; insurance; Kronos; labor relations; Lawson; leadership; managing; Medical Manager; meetings; Access; Excel; MS Office; Outlook; PowerPoint; Word; newsletter; Oracle; organizational development; payroll; PeopleSoft; performance reviews; personnel; policies; Progress; QuickBooks; record keeping; recruiting; reporting; retail; safety; teamwork; troubleshoot; 2000
Experience: Sr. HR Generalist at Company Name (01/2012 - Current) : Manage and Coordinate HR Support to 5 Resorts throughout South and Central Florida. Enforce company's policies and procedures for 2000+ employees, in conjunction with the bargaining agreement. Responsible for short and long term planning and management of the Human Resources function. Recommend the department's budget and manage expenses within approved budget constraints. Major areas of responsibility/management include, but are not limited to, employment, wage and salary administration, benefits, training, employee/labor relations, organizational development and payroll. Work closely with Resorts General Manager implementing, achieving and maintaining the Resort's goals and objectives. Participate in total Resort management as a member of the Resort Executive Team. Key Accomplishments: Created and implemented a training program for managers and supervisors including topics such as; employee motivation, effective leadership, completing disciplinary actions and performance reviews. Satisfied record keeping requirements evaluated during annual HR Audit. Reduce turnover rate by improving recruitment strategies, effective interviewing and proper selection. Improve employee relations events increasing employee participation and satisfaction. | Office Manager at Company Name (01/2010 - 01/2011) : Responsible for recruiting, interviewing, and hiring as well as monitoring payroll for over 60 retail employees. Managed workers compensation cases for all employees. Maintain HRIS database and 200+ personnel files. Conducted reference checks and performed new hire and safety orientation for new employees. Administer Personal Time Off and Sick Time records in the HRIS database for over 4000 employees in 4 states. Ran and audited weekly benefits reports. Acted as a liaison between benefit vendors and employees to resolve and troubleshoot claims issues. Issue monthly and quarterly workers compensation reports to senior management. Maintained OSHA logs and acted as a liaison between the carrier and the injured employees. Conducted new hire benefits orientation and organized annual benefits fair. Key Accomplishments: Developed and implemented PTO plans and Sick Time Plans for groups of employees that were currently not being tracked in the HRIS database. Discovered and corrected a $200,000 error in reporting reserves for workers compensation claims. Redesigned and updated the open enrollment and new hire benefits newsletter. Provide assistance to the Benefits Manager in creating a companywide wellness program. | HR Specialist at Company Name (01/2008 - 01/2010) : Promoted company wide a broad range of HR functions; Job Fairs and , administering benefits, overseeing disciplinary actions, and managing HR records. Co-chaired annual flex-enrollment meetings, resolved conflicts between employees and insurance carriers, coordinated health fairs to promote employee wellness and performed exit interviews. Worked with senior management to create HR policies and procedures; recruit employees; create group benefits databases; and develop orientation, training and incentive programs. Key Accomplishments: Foster a teamwork/open-door environment conducive to positive dialogue across the organization. Personal efforts were cited as the driving force behind branch's employee-retention rate of 89% within an industry where high turnover is the norm. Devise creative and cost-effective incentive and morale-boosting programs (including special events and a tiered awards structure) that increased employee satisfaction and productivity. Reduced benefits costs by 15% annually through meticulous recordkeeping and ensuring that company did not pay for benefits for which employees were ineligible.
Education: Master of Science in Industrial/Organization Psychology at University of Phoenix; Bachelor of Arts in Business Administration (Human Resources Management) at InterAmerican University of Puerto Rico
Certifications: Certified Mouth Swab- Drug test facilitator
Summary: Quality-driven analytical professional who delivers consistent and successful results in HR affairs, including recruitment and retention, staff development, safety and health, mediation, conflict resolution, benefits and compensation, HR audit and records management, HR policies development and legal compliance. Highlights HRIS (Kronos, Lawson, PeopleSoft, QuickBooks, HBI, ADP & Oracle) MS Office (Word, Excel, PowerPoint, Access, Outlook), EMR, Medical Manager. Certified Mouth Swab- Drug test facilitator Accomplishments Created and implemented a training program for managers and supervisors including topics such as; employee motivation, effective leadership, completing disciplinary actions and performance reviews. Satisfied record keeping requirements evaluated during annual HR Audit. Reduce turnover rate by improving recruitment strategies, effective interviewing and proper selection. Improve employee relations events increasing employee participation and satisfaction

===== Top 2 matching job offers =====

--- 💼 Found offers : 3036887367899999 ---
Similarity score : 0.1874
Job Title: Financial Analyst
Experience: 3 to 13 Years
Qualifications: BBA
Job Description: Financial Planners help clients achieve their financial goals by providing personalized financial advice and investment strategies. They assess clients financial situations, develop financial plans, and offer recommendations on savings, investments, and retirement planning.
Responsibilities: Assist clients with financial planning, investment strategies, and retirement planning. Conduct comprehensive financial assessments. Provide personalized financial advice and recommendations.
Work Type: Intern
Salary Range: $60K-$101K

--- 💼 Found offers : 2527447584617389 ---
Similarity score : 0.1812
Job Title: Accountant
Experience: 4 to 11 Years
Qualifications: MBA
Job Description: Financial Accountants handle financial records, prepare financial statements, and ensure compliance with accounting standards. They analyze financial data to provide accurate financial reports and support decision-making within the organization.
Responsibilities: Maintain financial records, prepare financial statements, and ensure compliance with accounting standards and regulations. Reconcile accounts and analyze financial data. Assist with financial audits.
Work Type: Part-Time
Salary Range: $57K-$128K
===== Selected resume =====
Skills: Training and development; Employee relations; Compensation administration; Performance management strategies; Human resources audits; Maintains confidentiality; HRMS; National Human Resources Association; Homeowners insurance knowledge; Excellent communicator; Deadline-driven; Marketing and sales specialist; New program and promotion implementation; Procedure development; Human Resources Information Systems (HRIS)

In [32]:
print("Comparison of approaches:")
print("ST with smaller resumes embedding: ", results_ST_small)
print("D2V with smaller resumes embedding: ", results_D2V_small)
print("ST with bigger resumes embedding: ", results_ST_big)
print("D2V with bigger resumes embedding: ", results_D2V_big)

Comparison of approaches:
ST with smaller resumes embedding:  [0.5964137613773346, 0.6209318339824677, 0.5719872713088989, 0.5163479745388031, 0.544945478439331, 0.46320840716362, 0.6294699609279633, 0.4644496589899063, 0.5503432154655457, 0.45751872658729553, 0.49061156809329987, 0.5133502185344696, 0.49668553471565247, 0.461374893784523, 0.4703637510538101, 0.493312269449234, 0.5263482928276062, 0.49442118406295776, 0.5195238590240479, 0.538997232913971]
D2V with smaller resumes embedding:  [0.20927492529153824, 0.23812918365001678, 0.14345034211874008, 0.08224032074213028, 0.17131010442972183, 0.177726611495018, 0.21740764379501343, 0.2201634868979454, 0.17724590748548508, 0.18095484375953674, 0.19698191434144974, 0.19603731483221054, 0.17943106591701508, 0.17934858798980713, 0.20103824138641357, 0.17173238098621368, 0.15561378747224808, 0.187616266310215, 0.2653256356716156, 0.20255490392446518]
ST with bigger resumes embedding:  [0.6123619973659515, 0.6074380278587341, 0.599783331155777, 0.6443275213241577, 0.6091620326042175, 0.500721737742424, 0.5681938529014587, 0.4764220118522644, 0.5903927981853485, 0.48413220047950745, 0.5453899204730988, 0.6240392029285431, 0.5267955958843231, 0.45653051137924194, 0.499116450548172, 0.5448706746101379, 0.5744965076446533, 0.5886414349079132, 0.5538358092308044, 0.4886465072631836]
D2V with bigger resumes embedding:  [0.1995595246553421, 0.15224464982748032, 0.2132802978157997, 0.1843034252524376, 0.16128132492303848, 0.16269299387931824, 0.16196231544017792, 0.21434075385332108, 0.16777801513671875, 0.17392423003911972, 0.12498706579208374, 0.28531843423843384, 0.13430248945951462, 0.2214116007089615, 0.22025278955698013, 0.21392440795898438, 0.22189730405807495, 0.1466299444437027, 0.15975414216518402, 0.13776061683893204]

In [49]:
jobs_index = faiss.read_index("./data/jobs_index.faiss")
with open("./data/jobs_index_mapping.json", "r") as f:
    jobs_mapping = {int(k): v for k, v in json.load(f).items()}

resume_index = faiss.read_index("./data/resume_index.faiss")
with open("./data/resume_index_mapping.json", "r") as f:
    resume_mapping = json.load(f)

model = SentenceTransformer("all-MiniLM-L6-v2")

def reconstruct_embeddings(index):
    embeddings = np.zeros((index.ntotal, index.d), dtype=np.float32)
    for i in range(index.ntotal):
        index.reconstruct(i, embeddings[i])
    return embeddings

resume_json_folder = "./data/resume_extract_text"
resume_data = {}

for fname in os.listdir(resume_json_folder):
    if fname.lower().endswith(".txt"):
        path = os.path.join(resume_json_folder, fname)
        with open(path, "r", encoding="utf-8") as f:
            data = f.read()
        resume_data[fname] = data

jobs_df = pd.read_csv("./data/job_offer/datasets/ravindrasinghrana/job-description-dataset/versions/1/job_descriptions.csv")
result_df_list=[]

cv_embeddings = reconstruct_embeddings(resume_index)
job_embeddings = reconstruct_embeddings(jobs_index)
all_embeddings = np.vstack([cv_embeddings, job_embeddings])
results_ST_small=[]

cv_index=200
cv_filename = resume_mapping[cv_index]

print("\n===== Selected resume =====")
if cv_filename in resume_data:
    print(resume_data[cv_filename])

cv_emb = cv_embeddings[cv_index:cv_index+1]
distances, indices = jobs_index.search(cv_emb, 5)

results = [
    {"job_index": int(idx), "job_id": jobs_mapping[int(idx)], "score": float(score)}
    for score, idx in zip(distances[0], indices[0])
]

print(f"\n===== Top 5 matching job offers =====")
for r in results:
    job_id = r["job_id"]
    print(f"\n--- 💼 Found offers : {job_id} ---")
    print(f"Similarity score : {r['score']:.4f}")
    
    job_row = jobs_df[jobs_df["Job Id"] == job_id]
    job_result=job_row[["Job Title", "Company", "Experience",
        "Qualifications", "skills", "Job Description", "Responsibilities",
        "Work Type", "Salary Range"]]
    result_df_list.append(job_result)

    if len(job_row) == 0:
        print("⚠️ Offer not found in jobs_df")
        continue
    
    row = job_row.iloc[0]
    
    fields_to_show = [
        "Job Title", "Company Name", "Location", "Experience",
        "Qualifications", "Skills", "Job Description", "Responsibilities",
        "Work Type", "Salary Range"
    ]
    
    for col in fields_to_show:
        if col in row and not pd.isna(row[col]):
            print(f"{col}: {row[col]}")

result_df=result_df_list[0]
for i in range(1,len(result_df_list)):
    result_df=pd.concat([result_df,result_df_list[i]],ignore_index=True)

===== Selected resume =====
Skills: Leadership; Communication; Business operations; Client account management; Budgeting; Negotiation; Employee relations; Self-motivation; Market research and analysis; Customer orientation; Microsoft Family Products; Customer CRM; GPO and IDN targeting; Vendor and Distributor Relations; National Business Development; Regional Business Development; Local Business Development; Forecasting; C-Suite Executive Targeting; Sales Management; Problem Solving
Experience: Director of National Sales- US. Healthcare at Company Name; National Accounts Manager- Northeast Region at Company Name; Business Development Manager at Company Name
Education: B.A. in Marketing at Bloomsburg University
Certifications: Karrass Effective Negotiating Seminar; Linde Pro Sales Training; Sales Performance International-Solution Sales; Sales Performance Internal-Management Training; Challenger Sales Training; Completed Advanced Sales Training I; Consultative Sales Training; Situational Leadership I; Behavioral Interviewing Training; Advanced Lead Generation Techniques and Diversity Training
Summary: SALES AND BUSINESS DEVELOPMENT EXECUTIVE Successful in sales management and business development at the local, regional, and national levels. Hands-on manager with highly developed negotiation skills. Provide sound budgeting, financial, and forecasting management. Creative problem solver who drives revenue, resolves conflict, and consistently exceeds sales goals.

===== Top 5 matching job offers =====

--- 💼 Found offers : 1750518493773044 ---
Similarity score : 0.6868
Job Title: Business Development Manager
Experience: 5 to 10 Years
Qualifications: PhD
Job Description: A Sales Manager leads and guides the sales team, sets sales targets, develops sales strategies, and monitors performance to achieve revenue and growth objectives.
Responsibilities: Lead and manage a sales team, set sales goals, and develop sales strategies. Identify new business opportunities and target markets. Build and maintain client relationships.
Work Type: Contract
Salary Range: $65K-$92K

--- 💼 Found offers : 991876011802800 ---
Similarity score : 0.6815
Job Title: Business Development Manager
Experience: 4 to 8 Years
Qualifications: BA
Job Description: A Sales Manager leads and guides the sales team, sets sales targets, develops sales strategies, and monitors performance to achieve revenue and growth objectives.
Responsibilities: Lead and manage a sales team, set sales goals, and develop sales strategies. Identify new business opportunities and target markets. Build and maintain client relationships.
Work Type: Contract
Salary Range: $58K-$82K

--- 💼 Found offers : 336831904414436 ---
Similarity score : 0.6804
Job Title: Business Development Manager
Experience: 3 to 12 Years
Qualifications: BCA
Job Description: A Sales Manager leads and guides the sales team, sets sales targets, develops sales strategies, and monitors performance to achieve revenue and growth objectives.
Responsibilities: Lead and manage a sales team, set sales goals, and develop sales strategies. Identify new business opportunities and target markets. Build and maintain client relationships.
Work Type: Contract
Salary Range: $55K-$96K

--- 💼 Found offers : 1860884116431098 ---
Similarity score : 0.6798
Job Title: Business Development Manager
Experience: 2 to 11 Years
Qualifications: BBA
Job Description: A Sales Manager leads and guides the sales team, sets sales targets, develops sales strategies, and monitors performance to achieve revenue and growth objectives.
Responsibilities: Lead and manage a sales team, set sales goals, and develop sales strategies. Identify new business opportunities and target markets. Build and maintain client relationships.
Work Type: Full-Time
Salary Range: $65K-$112K

--- 💼 Found offers : 1759480494318066 ---
Similarity score : 0.6792
Job Title: Business Development Manager
Experience: 0 to 13 Years
Qualifications: M.Com
Job Description: A Sales Manager leads and guides the sales team, sets sales targets, develops sales strategies, and monitors performance to achieve revenue and growth objectives.
Responsibilities: Lead and manage a sales team, set sales goals, and develop sales strategies. Identify new business opportunities and target markets. Build and maintain client relationships.
Work Type: Intern
Salary Range: $64K-$125K

In [50]:
results

[{'job_index': 50229, 'job_id': 1750518493773044, 'score': 0.6867740154266357},
 {'job_index': 47044, 'job_id': 991876011802800, 'score': 0.6814556121826172},
 {'job_index': 30386, 'job_id': 336831904414436, 'score': 0.6803520917892456},
 {'job_index': 28912, 'job_id': 1860884116431098, 'score': 0.6798303723335266},
 {'job_index': 85050, 'job_id': 1759480494318066, 'score': 0.6791889667510986}]

In [51]:
result_df

,Job Title,Company,Experience,Qualifications,skills,Job Description,Responsibilities,Work Type,Salary Range
0,Business Development Manager,ITC Limited,5 to 10 Years,PhD,Sales management Sales strategy development Te...,A Sales Manager leads and guides the sales tea...,"Lead and manage a sales team, set sales goals,...",Contract,$65K-$92K
1,Business Development Manager,Dell Technologies,4 to 8 Years,BA,Sales management Sales strategy development Te...,A Sales Manager leads and guides the sales tea...,"Lead and manage a sales team, set sales goals,...",Contract,$58K-$82K
2,Business Development Manager,Ford Motor Company,3 to 12 Years,BCA,Sales management Sales strategy development Te...,A Sales Manager leads and guides the sales tea...,"Lead and manage a sales team, set sales goals,...",Contract,$55K-$96K
3,Business Development Manager,Principal Financial,2 to 11 Years,BBA,Sales management Sales strategy development Te...,A Sales Manager leads and guides the sales tea...,"Lead and manage a sales team, set sales goals,...",Full-Time,$65K-$112K
4,Business Development Manager,United States Steel,0 to 13 Years,M.Com,Sales management Sales strategy development Te...,A Sales Manager leads and guides the sales tea...,"Lead and manage a sales team, set sales goals,...",Intern,$64K-$125K

In [57]:
prompt = f"""
You are an experienced recruiter.

A candidate has the following resume:

{resume_data[cv_filename]}

Based on vector similarity search, the following job offers were selected and are in this dataframe: {result_df}

Your task is ONLY to explain and interpret these results.

For EACH job offer selected, meaning each line of the dataset:
1. Explain why the resume is relevant
2. Highlight matching skills and experience
3. Mention potential gaps or risks
4. Give a short, honest recommendation

DO NOT re-score.
DO NOT re-rank.
DO NOT invent new jobs.
"""
ollama_model = os.environ.get("OLLAMA_MODEL", "mistral")
llm = Ollama(model=ollama_model)

explanation = llm.invoke(prompt)
print(explanation)

 1. **Job Title: Business Development Manager at ITC Limited**
   - Relevance: The candidate's skills and experience align well with the role of a Business Development Manager, particularly in sales management, client account management, negotiation, employee relations, business operations, and budgeting.
   - Matching Skills and Experience: Leadership, Communication, Sales Management, Business Operations, Client Account Management, Budgeting, Negotiation, Employee Relations. The candidate's experience as a Director of National Sales and Business Development Manager at various companies demonstrates relevant experience.
   - Potential Gaps or Risks: It appears that the candidate does not have specific experience in the pharmaceutical or FMCG industry where ITC Limited operates, which could be a potential risk to the company. However, given the transferable nature of sales and business development skills across industries, this gap might not significantly impact their ability to perform the job.
   - Recommendation: The candidate's diverse skills and extensive experience make them a strong fit for this role. It would be beneficial for them to research ITC Limited's industry and specific products to better understand the context of the company and tailor their approach accordingly.

2. **Job Title: Business Development Manager at Dell Technologies**
   - Relevance: The candidate's skills and experience align with the role of a Business Development Manager, particularly in sales management, client account management, negotiation, budgeting, and GPO and IDN targeting.
   - Matching Skills and Experience: Leadership, Communication, Sales Management, Client Account Management, Negotiation, Budgeting, GPO and IDN Targeting. The candidate's experience as a Director of National Sales and Business Development Manager at various companies demonstrates relevant experience.
   - Potential Gaps or Risks: It is unclear from the provided information whether the candidate has specific experience in technology or IT sales, which could be a potential risk to the company. However, given the transferable nature of sales and business development skills across industries, this gap might not significantly impact their ability to perform the job.
   - Recommendation: The candidate's diverse skills and extensive experience make them a strong fit for this role. It would be beneficial for them to research Dell Technologies' products and services to better understand the context of the company and tailor their approach accordingly.

3. **Job Title: Business Development Manager at Ford Motor Company**
   - Relevance: The candidate's skills and experience align with the role of a Business Development Manager, particularly in sales management, client account management, negotiation, budgeting, and vendor and distributor relations.
   - Matching Skills and Experience: Leadership, Communication, Sales Management, Client Account Management, Negotiation, Budgeting, Vendor and Distributor Relations. The candidate's experience as a Director of National Sales and Business Development Manager at various companies demonstrates relevant experience.
   - Potential Gaps or Risks: It is unclear from the provided information whether the candidate has specific experience in the automotive industry, which could be a potential risk to the company. However, given the transferable nature of sales and business development skills across industries, this gap might not significantly impact their ability to perform the job.
   - Recommendation: The candidate's diverse skills and extensive experience make them a strong fit for this role. It would be beneficial for them to research Ford Motor Company's products and services to better understand the context of the company and tailor their approach accordingly.

4. **Job Title: Business Development Manager at Principal Financial**
   - Relevance: The candidate's skills and experience align well with the role of a Business Development Manager, particularly in sales management, client account management, negotiation, budgeting, and forecasting.
   - Matching Skills and Experience: Leadership, Communication, Sales Management, Client Account Management, Negotiation, Budgeting, Forecasting. The candidate's experience as a Director of National Sales and Business Development Manager at various companies demonstrates relevant experience.
   - Potential Gaps or Risks: It is unclear from the provided information whether the candidate has specific experience in the financial services industry, which could be a potential risk to the company. However, given the transferable nature of sales and business development skills across industries, this gap might not significantly impact their ability to perform the job.
   - Recommendation: The candidate's diverse skills and extensive experience make them a strong fit for this role. It would be beneficial for them to research Principal Financial's products and services to better understand the context of the company and tailor their approach accordingly.

5. **Job Title: Business Development Manager at United States Steel**
   - Relevance: The candidate's skills and experience align with the role of a Business Development Manager, particularly in sales management, client account management, negotiation, budgeting, and national business development.
   - Matching Skills and Experience: Leadership, Communication, Sales Management, Client Account Management, Negotiation, Budgeting, National Business Development. The candidate's experience as a Director of National Sales and Business Development Manager at various companies demonstrates relevant experience.
   - Potential Gaps or Risks: It is unclear from the provided information whether the candidate has specific experience in the steel industry, which could be a potential risk to the company. However, given the transferable nature of sales and business development skills across industries, this gap might not significantly impact their ability to perform the job.
   - Recommendation: The candidate's diverse skills and extensive experience make them a strong fit for this role. It would be beneficial for them to research United States Steel's products and services to better understand the context of the company and tailor their approach accordingly.